joincivil/Civil

- .circleci/config.yml
- package.json
- packages/civil.ts/package.json
- packages/contracts/package.json
- packages/debug-ui/gulpfile.js
- packages/debug-ui/package.json
- yarn.lock
The tests will fail until #12 is merged due to previous merge without CI tests run, making tests fail due to empty files (commented out) in test directories.
> Improved scripts in npm packages and their yarn support

- packages/core/src/civil.ts
- packages/core/src/utils/web3wrapper.ts
- packages/dev-utils/src/test/index.ts
The only thing that still links web3wrapper and @joincivil/core is the Receipt decoding. Otherwise, we could use web3 wrapper in other Civil's repos and packages
> Closed-boxed web3wrapper

- packages/contracts/conf/config.json
- packages/contracts/migrations/2_optional_for_test.ts
- packages/contracts/migrations/4_deploy_plcr.ts
- packages/contracts/migrations/5_deploy_parameterizer.ts
- packages/contracts/migrations/6_registry.ts
- packages/contracts/migrations/utils/consts.ts
instead of deploying a new one every time
> using deployed token for rinkeby migrations

- packages/dapp/src/components/listing/ListingDetail.tsx
- packages/dapp/src/components/utility/TransactionButton.tsx
was previously reading backward, also setImmediate is better at making sure setState happens before navigate
> fix transaction button for reals reals

- packages/contracts/test/tcr/registry/apply.ts
- packages/contracts/test/tcr/registry/challenge.ts
- packages/contracts/test/tcr/registry/deposit.ts
- packages/contracts/test/tcr/registry/exit.ts
- packages/contracts/test/tcr/registry/withdraw.ts
- packages/contracts/test/tcr/registryWithAppeals/apply.ts
- packages/contracts/test/tcr/registryWithAppeals/challengeGrantedAppeal.ts
- packages/contracts/test/tcr/registryWithAppeals/requestAppeal.ts
- packages/contracts/test/utils/contractutils.ts
- add unit tests that increase code coverage when user making transaction has not properly approved registry as a spender of token
- a few more random unit tests for more code coverage
> More Unit Tests for TCR contracts

- .solcover.js
- updating .solcover.js to skip files that we had to copy into our repo from EPM & zeppelin due to doxity limitations
> updating .solcover.js 

- packages/dapp/package.json
- packages/dapp/src/apis/civilTCR.ts
- packages/dapp/src/components/newsroom/NewsroomManagement.tsx
- Change `homepage` to `/` so the dapp stops using relative paths for
generated assets files
- Grab deposit amounts from the Parameterizer when approve/applying to
TCR. Note: This is due to some unidentifed weirdness w/ `BigNumber`.
We'll fix this for real in a fturue update
> Fixes for some annoying bugs in the DApp

- packages/core/src/utils/listingDataHelpers/challengeHelper.ts
- packages/core/src/utils/listingDataHelpers/listingHelper.ts
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/listinglist/ListingsInProgress.tsx
- packages/dapp/src/reducers/index.ts
- packages/dapp/src/reducers/listings.ts
also:
-  fixing bug in core related to can challenge be resolved
> adding sub-tabs for listings in progress

- packages/dapp/src/helpers/listingEvents.ts
Update so the `listingsInApplication` event stream loads from the beginning, and not from the `getApplicationMaximumLengthInBlocks` helper method.
This update addresses the issue where applications in various Appeal and Resolve Challenge phases weren't getting loaded into the DApp.
> DApp: Look at all listing applications since the beginning

- packages/dapp/src/components/parameterizer/Proposal.tsx
- packages/dapp/src/helpers/parameterizer.ts
This updates fixes a couple of bugs that were preventing the Reparameterization Proposal view from rendering, which in turn would prevent users acting on proposals.
> Hotfixes for bugs in the Reparameterization Proposal view

- packages/components/src/DetailTransactionButton.stories.tsx
- packages/components/src/DetailTransactionButton.tsx
- packages/components/src/ProgressModalContent.tsx
- packages/components/src/TransactionButton.tsx
- packages/dapp/src/components/newsroom/Newsroom.tsx
This update also includes default Success, Error, In Progress modal content, as well as hooks for implementing custom modal content for Transactions that are initiated via the `TransactionButton`.
It also adds a `try/catch` to the `executeTransactions()` method as a hook to trigger display of error modals.
> Refactor Progress modal to live in Transaction button by default

- packages/core/src/contracts/newsroom.ts
- even core can't make big numbers correctly, so use the helper function to make one when creating newsroom contract via factory
> Fix Deploy Newsroom

- packages/dapp/src/components/newsroom/SignConstitution.tsx
Grab the user's eth address from the (new) correct spot in the redux store when checking if the user is an owener
> Fix `isOwner` check in Sign Consitution view

- packages/core/doc/examples/low-level/multisig.ts
- packages/core/doc/examples/low-level/typed_contracts.ts
- packages/core/src/civil.ts
- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/utils/ethapi.ts
- packages/dapp/src/actionCreators/network.ts
- packages/dapp/src/components/Main.tsx
- packages/dapp/src/components/Parameterizer.tsx
- packages/dapp/src/components/listing/ChallengeDetail.tsx
- packages/dapp/src/components/listing/Listing.tsx
- packages/dapp/src/components/listing/ListingHistory.tsx
- packages/dapp/src/components/listinglist/ListingListItem.tsx
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/listinglist/ListingsInProgress.tsx
- packages/dapp/src/components/listinglist/MyActivity.tsx
- packages/dapp/src/components/navbar/NavBar.tsx
- packages/dapp/src/components/parameterizer/Proposal.tsx
- packages/dapp/src/components/parameterizer/Proposals.tsx
- packages/dapp/src/reducers/index.ts
- packages/dapp/src/reducers/network.ts
- Continously poll for network changes and subscribe to changes. 
- When network changes, clear almost all of redux store and restart subscriptions. 
- Add error bar when not on rinkeby.
> Network Check

- packages/components/src/TransactionButton.tsx
- reset state of transaction button if transaction has error of some kind
- https://app.clubhouse.io/civil/story/1298/dapp-transaction-button-gets-into-bad-state-when-transaction-fails-or-is-canceled
- https://app.clubhouse.io/civil/story/1299/transaction-button-releases-when-you-reject
> Transaction Button Fix

- packages/dapp/src/components/listing/Listing.tsx
- packages/dapp/src/components/listinglist/ListingListItem.tsx
- packages/dapp/src/reducers/index.ts
fixing it by adding a namespace to newsroom manager was getting to complicated
> move newsroom manager reducers to top level

- packages/dapp/package.json
Remove `@types/react` and `@types/react-dom` resolutions in the Dapp's package.json
> Fix React typing dependency issues

- packages/components/src/ListingDetailPhaseCard/ChallengeAwaitingAppealDecisionCard.tsx
- packages/components/src/ListingDetailPhaseCard/ChallengeRequestAppealCard.tsx
- packages/components/src/ListingDetailPhaseCard/ChallengeResults.tsx
- packages/components/src/ListingDetailPhaseCard/CommitVote.tsx
- packages/components/src/ListingDetailPhaseCard/InApplicationCard.tsx
- packages/components/src/ListingDetailPhaseCard/InApplicationResolveCard.tsx
- packages/components/src/ListingDetailPhaseCard/RejectedCard.tsx
- packages/components/src/ListingDetailPhaseCard/RevealVote.tsx
- packages/components/src/ListingDetailPhaseCard/WhitelistedCard.tsx
- packages/core/src/contracts/newsroom.ts
- packages/dapp/src/App.tsx
- packages/dapp/src/components/listing/AppealDetail.tsx
- packages/dapp/src/components/listing/ChallengeDetail.tsx
- packages/dapp/src/components/listing/Listing.tsx
- packages/dapp/src/components/listing/ListingChallengeStatement.tsx
- packages/dapp/src/components/listing/ListingHistory.tsx
- packages/dapp/src/components/listing/styledComponents.tsx
- packages/dapp/src/components/tabs/Tab.tsx
- packages/dapp/tslint.json
- Fix grey buttons in DApp
- Don't display 'NaN' in Challenge Results chart
- Fix success modal for Commit Vote (by only having one transaction button in the DOM)
- Fix progress modal messaging for Approve For Request Appeal
- Add try/catch to `contentProvider.get()` call in Newsroom contract, to catch `FallbackProvider` error that can kill the DApp
- Remove newsroom deposit text from Phase cards
- Add some basic tab content / challenge statement styles to Listing Detail page
- Fix bug where Awaiting Appeal Decision and Resolve Appeal would appear at the same time
> Minor fixes and tweaks for Playtest

- packages/contracts/contracts/tcr/CivilTCR.sol
- packages/contracts/contracts/tcr/Government.sol
- Adding safety checks for government parameters in constructor and transferGovernment function
- avoid bypassing static type system for government parameter
> Responding to Audit Findings 3.30, 3.31, 3.32

- packages/contracts/contracts/tcr/AddressRegistry.sol
- packages/contracts/contracts/tcr/CivilTCR.sol
- packages/contracts/test/tcr/registry/updateStatus.ts
- packages/contracts/test/tcr/registry/userStories.ts
- packages/contracts/test/tcr/registryWithAppeals/apply.ts
- packages/contracts/test/tcr/registryWithAppeals/requestAppeal.ts
- packages/contracts/test/utils/contractutils.ts
- switching meaning of 'voting.isPassed' in TCR contracts to match standard implementation
- fixing unit tests after changes to contracts
> Respond to Audit Finding 3.35

- packages/components/src/ListingDetailPhaseCard/ListingDetailsPhaseCard.stories.tsx
- packages/components/src/ListingDetailPhaseCard/RejectedCard.tsx
- packages/components/src/ListingDetailPhaseCard/WhitelistedCard.tsx
- packages/core/src/contracts/tcr/listing.ts
- packages/dapp/src/actionCreators/listings.ts
- packages/dapp/src/components/listing/Listing.tsx
- packages/dapp/src/components/listing/ListingCharter.tsx
- packages/dapp/src/components/listing/ListingPhaseActions.tsx
- packages/dapp/src/components/listing/WhitelistedDetail.tsx
- packages/dapp/src/components/utility/HigherOrderComponents.tsx
- packages/dapp/src/reducers/index.ts
- packages/dapp/src/reducers/listings.ts
- packages/dapp/src/selectors/index.ts
- Display the listing whitelisted / rejected timestamps where appropriate
- Render the newsroom charter in the 'About' tab on the listing detail page
> DApp UI updates: Whitelisted / Rejected timestamps + Newsroom charter

- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/contracts/tcr/voting.ts
- packages/dapp/src/actionCreators/listings.ts
- packages/dapp/src/actionCreators/ui.ts
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/helpers/listingEvents.ts
- packages/dapp/src/reducers/index.ts
- packages/dapp/src/reducers/listings.ts
- load existing listings from past events separately from future events
- display "loading" while loading, so we don't get half-loaded newsrooms rendering
> Loading Steps

- packages/core/src/content/eventstorageprovider.ts
- packages/core/src/contracts/newsroom.ts
- packages/core/src/contracts/tcr/challenge.ts
- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/contracts/tcr/eip20.ts
- packages/core/src/contracts/tcr/government.ts
- packages/core/src/contracts/tcr/listing.ts
- packages/core/src/contracts/tcr/parameterizer.ts
- packages/core/src/contracts/tcr/voting.ts
- packages/dapp/src/helpers/listingEvents.ts
- packages/utils/src/civilHelpers.ts
Add and implement `getDefaultFromBlock()` to `@joincivil/utils`, which returns the block number of the TCR genesis block
This is update is to play nicer with Infura's APIs by starting our sniffing of `getLogs` from the genesis of the TCR, and not the beginning of the log
> Add and implement getDefaultFromBlock()

- packages/core/README.md
Came to fix `civil.newsroomAtUntruested` typo and then couldn't stop.
Obviously there is a ton to do with docs and examples but I wanted to just drop something in here that works.
> Update core readme example with something that works

- packages/newsroom-manager/src/Newsroom.tsx
Otherwise it breaks if you don't supply a theme.
> Provide default (empty) theme for newsroom manager [ch2211]

- packages/components/src/ListingDetailPhaseCard/AppealAwaitingDecisionCard.tsx
- packages/core/src/contracts/multisig/multisig.ts
- packages/core/src/contracts/tcr/appeal.ts
- packages/core/src/contracts/tcr/challenge.ts
- packages/core/src/contracts/tcr/council.ts
- packages/core/src/contracts/tcr/listing.ts
- packages/core/src/index.ts
- packages/core/src/types.ts
- packages/dapp/src/actionCreators/government.ts
- packages/dapp/src/apis/civilTCR.ts
- packages/dapp/src/components/Main.tsx
- packages/dapp/src/components/listing/AppealDetail.tsx
- packages/dapp/src/components/listing/ChallengeDetail.tsx
- packages/dapp/src/helpers/government.ts
- packages/dapp/src/reducers/government.ts
- packages/dapp/src/reducers/index.ts
- rather than forcing council members to go to Gnosis, now we load up any pending council transactions into redux, as well as the raw tx data for any appeals
- when rendering the appeal data, if the raw tx data matches anything in the council multisig, go through confirm tx flow instead of submit tx to multisig
> Council UX Improvement

- packages/contracts/contracts/tcr/CivilTCR.sol
- overriding determineReward in CivilTCR.sol to get different token amounts when challenge was overridden
> Respond to Extended Audit Issue 71 and 72

- packages/dapp/src/components/listing/ListingCharter.tsx
- packages/dapp/src/components/listing/ListingHeader.tsx
- packages/dapp/src/components/listinglist/ListingListItem.tsx
Add temporary fix to properly render the older charter format after the update to parse the charter into a JS object in `core`
> DApp: Render legacy charter format

- packages/newsroom-manager/src/CreateCharterPartOne.tsx
- packages/newsroom-manager/src/CreateCharterPartTwo.tsx
- packages/newsroom-manager/src/Newsroom.tsx
- packages/newsroom-manager/src/SignConstitution.tsx
- packages/newsroom-manager/src/actionCreators.ts
- packages/newsroom-manager/src/reducers.ts
- Lift state for charter up into parent `Newsroom` component
- Persist charter to CMS or `localStorage` as side effect of update action
- Refactor charter step completion checks
- etc.
> Refactor charter state and completion

- packages/core/src/contracts/tcr/civilTCR.ts
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/listinglist/RejectedListingListContainer.tsx
- packages/dapp/src/components/listinglist/RejectedListingListRedux.tsx
- packages/dapp/src/helpers/listingEvents.ts
adding rejected listings components with graphql query option (basically identical to the way whitelisted listings work). little fixes elsewhere
> Rejected Listings via GraphQL & other fixes

- packages/core/src/civil.ts
- packages/core/src/contracts/newsroom.ts
- packages/core/src/contracts/tcr/appeal.ts
- packages/core/src/contracts/tcr/appealChallenge.ts
- packages/core/src/contracts/tcr/challenge.ts
- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/contracts/tcr/listing.ts
- packages/core/src/types.ts
- packages/dapp/src/components/listing/ListingChallengeStatement.tsx
- packages/dapp/src/components/listinglist/ListingListItem.tsx
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/listinglist/ListingsInProgressContainer.tsx
- packages/dapp/src/components/listinglist/WhitelistedListingItem.tsx
- packages/dapp/src/helpers/listingEvents.ts
- packages/dapp/src/helpers/queryTransformations.ts
- packages/dapp/src/redux/actionCreators/newsrooms.ts
- packages/dapp/src/redux/reducers/newsrooms.ts
- packages/newsroom-manager/src/contentViewer/Revision.tsx
just return URI associated with statements in `core` and then get the actual content in the dapp, whether URI came from `core` or `graphql`
> Statement Loading Refactors

- packages/newsroom-manager/src/CompleteYourProfile.tsx
- packages/newsroom-manager/src/CreateCharterPartOne.tsx
- packages/newsroom-manager/src/NewsroomUser.tsx
- packages/newsroom-manager/src/RosterMember.tsx
- packages/newsroom-manager/src/actionCreators.ts
- packages/newsroom-manager/src/reducers.ts
- packages/newsroom-manager/src/styledComponents.tsx
Various things that a) fix bugs, and b) should make probable transition to unified contract member/roster member interface smoother.
- Support roster members with no wallet address [ch2659]
- Ensure user data (name/bio/avatar/etc) is loaded properly for addresses that have just been added to contract [ch2689] [ch2690]
- Fix bug with duplicate members on roster [ch2674] and overall better/less buggy handling of relationship between contract members and roster members
- All contract members are now required to be on the roster
- Misc redux refactoring
- Some style/copy cleanup for contract members listing
> Refactor and bugfixes for contract member and roster management

- package.json
- packages/components/package.json
- packages/contracts/package.json
- packages/core/package.json
- packages/newsroom-manager/package.json
- yarn.lock
As pointed out int #630 event-stream 3.3.6 has malicious code injected that tries to attack bitcoin wallet software. See dominictarr/event-stream/issues/116
This PR upgrades npm-run-all to the latest version which does not depend on this malicious module
> Upgrade npm-run-all to remove malicious event-stream dependency

- packages/components/src/NavBar/NavBar.tsx
- packages/components/src/NavBar/NavDrawer.tsx
- packages/components/src/NavBar/types.ts
Add event listener that closes the Top Nav User Drawer if the user clicks outside of the drawer.
Addresses issue #635
> Improve behavior of Top Nav User Drawer

- packages/dapp/src/components/Dashboard/Dashboard.tsx
- packages/dapp/src/components/Parameterizer/index.tsx
- packages/dapp/src/components/listing/Listing.tsx
- packages/dapp/src/components/listing/RequestAppeal.tsx
- packages/dapp/src/components/listing/SubmitChallenge.tsx
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/utility/ScrollToTop.tsx
Add helper component to scroll the user back to the top of the window when they navigate to views that need that behavior
Implemented per React Router's documentation suggestion:
https://reacttraining.com/react-router/web/guides/scroll-restoration
Addresses Issue #634
> Scroll user to top of window on navigation change, when applicable

- packages/core/src/contracts/tcr/parameterizer.ts
- packages/dapp/src/components/Parameterizer/constants.ts
- packages/dapp/src/components/Parameterizer/index.tsx
- packages/utils/src/civilHelpers.ts
- packages/utils/src/viewHelpers.tsx
- removing pProcessBy parameter where necessary since it's no longer a parameter, but rather a constant
> Small Parameterizer UI cleanup

- packages/dapp/src/components/Dashboard/Dashboard.tsx
- packages/dapp/src/components/Parameterizer/index.tsx
- packages/dapp/src/components/listing/ListingRedux.tsx
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/listinglist/ListingsInProgress.tsx
This update adds (or restores) basic page titles, for improved usability. These page titles are also used by Coral Talk's admin interface that lists threads that need moderation.
Addresses issue #672
> Restore/add proper page `<title>` elements where applicable to the dapp

- packages/components/src/ToolTip.tsx
- Return to absolutely positioned via react portal so that they can escape restrictive parents
- Theme support + controlling width, text align, vertical offset, etc.
- Fix bugs causing tooltip to be aligned incorrectly in various places
- Fix overlarge hit box blocking hovering on adjacent things
I tested as many tooltips in the dapp as I could find, but some require pretty specific states so I didn't catch them all, however I think tooltips should be set up now that they just work, but keep an eye out and let me know if not!
> Refactor tooltips

- packages/components/src/UserStatement/RequestAppealStatement.tsx
- packages/components/src/UserStatement/SubmitAppealChallengeStatement.tsx
- packages/dapp/src/components/listing/ListingChallengeStatement.tsx
- packages/dapp/src/components/listing/ListingRedux.tsx
- packages/dapp/src/components/listing/RequestAppeal.tsx
Addresses #519 
Additionally, this update:
- fixes the rendering of Appeal Statement and Appeal Challenge Statement in the DApp
- makes the 'Discussions' tab the initially active tab, if a challenge is active for the listing
> Fix text for Request Appeal form

- packages/core/src/contracts/tcr/appeal.ts
- packages/core/src/contracts/tcr/challenge.ts
- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/types.ts
- packages/dapp/src/components/listing/ChallengeDetail.tsx
- packages/dapp/src/helpers/queryTransformations.ts
- packages/dapp/src/redux/actionCreators/challenges.ts
- packages/dapp/src/redux/reducers/challenges.ts
- packages/dapp/src/redux/reducers/index.ts
- refactoring how we get confirm appeal raw tx so it works whether loading via graphql or web3
> Confirm Appeal with GraphQL

- packages/components/src/ListingDetailPhaseCard/CommitVote.tsx
- packages/components/src/ListingDetailPhaseCard/RevealVote.tsx
- packages/components/src/ListingDetailPhaseCard/types.ts
- packages/components/src/input/SaltInput.tsx
- packages/dapp/src/components/listing/AppealChallengeDetail.tsx
- packages/dapp/src/components/listing/AppealChallengeRevealVote.tsx
- packages/dapp/src/components/listing/ChallengeDetail.tsx
- packages/dapp/src/components/listing/ChallengeRevealVote.tsx
This update fixes an issue where a user could not reveal a vote, if the vote / salt were not saved in localStorage.
Additionally, it includes:
- Refactoring of how the Reveal Vote cards get `salt` and `voteOption` from localStorage and set those values into local state for the relevant components
- Introduces use of the `user` prop as a `key` prop for Reveal Vote card components. When a `key` changes, the component is re-instantiated, so initializing the `salt` and `voteOption` in the constructor happens again, once the `user` prop is loaded from Redux. This is a slightly better fix for the race condition issue where the `user` prop would not be available to the component during initialization, so the `salt` and `voteOption` would not populate for those views.
- Refactoring and cleanup of …
> Fixes and clean up for Reveal Vote 

- packages/components/src/AuthenticatedRoute.tsx
- packages/components/src/index.ts
- packages/dapp/src/components/Account/UserInfo.tsx
- packages/dapp/src/components/Account/index.tsx
* Adds a helper that redirects if a user is not authenticated.
* Also has a param that reverses this functionality and only allows if they are *not* authenticated.
* Maybe a bit of overkill, but it calls the `currentUser` graphql query and redirects on (any) error.
> Authenticated routes 

- packages/components/src/ListingSummary/styledComponents.tsx
- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/types.ts
- packages/dapp/src/components/Dashboard/ActivityList.tsx
- packages/dapp/src/components/Dashboard/ActivityListAppealChallengeItem.tsx
- packages/dapp/src/components/Dashboard/ChallengesWithRewardsToClaim.tsx
- packages/dapp/src/components/Dashboard/ChallengesWithTokensToRescue.tsx
- packages/dapp/src/components/Dashboard/DashboardActivity.tsx
- packages/dapp/src/helpers/listingEvents.ts
- packages/dapp/src/redux/actionCreators/challenges.ts
- packages/dapp/src/redux/reducers/challenges.ts
- packages/dapp/src/redux/reducers/index.ts
- packages/dapp/src/selectors/index.ts
- adds appeal challenges to rescue and claim rewards for to my activity
- these do not necessarily render properly, the whole my activity section will be overhauled this sprint, but it does unblock users who want to transfer tokens out of voting contract
> *Rough* fix for appeal challenges my activity

- .circleci/config.yml
- When code is pushed to `master`, deploys new container with the dapp code to production namespace in GCP.  
- Keying off the `master` branch for now, but there was some discussion on continuous delivery instead of continuous deployment and keying off a `production` branch. We can debate that offline and make changes later, just want to get the production deployment ready.
CIVIL-185
> Add Production Push to CircleCI Config

- packages/components/src/PhaseCountdown/constants.ts
- packages/components/src/PhaseCountdown/textComponents.tsx
- packages/dapp/src/components/Dashboard/ActivityListAppealChallengeItem.tsx
- packages/dapp/src/components/listing/AppealChallengeResolve.tsx
- packages/dapp/src/components/utility/HigherOrderComponents.tsx
This updates includes:
- Fix for wrong challenge results displayed in Dashboard Activity Items. The Challenge Results component for these pages now uses the appropriate helper method from `@joincivil/core` to determine if a challenge succeeded
- Enables proper phase countdown rendering for Dashboard Activity Items that are in the various appeal phases with expiries
> Fixes for Dashboard page

- packages/components/src/ListingDetailPhaseCard/AppealAwaitingDecisionCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealChallengeCommitVoteCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealChallengeResolveCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealChallengeRevealVoteCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealDecisionCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealDecisionDetail.tsx
- packages/components/src/ListingDetailPhaseCard/AppealResolveCard.tsx
- packages/components/src/ListingDetailPhaseCard/types.ts
- packages/core/src/contracts/tcr/appeal.ts
- packages/core/src/types.ts
- packages/dapp/src/apis/civilTCR.ts
- packages/dapp/src/components/listing/AppealAwaitingDecision.tsx
- packages/dapp/src/components/listing/AppealChallengeCommitVote.tsx
- packages/dapp/src/components/listing/AppealChallengeResolve.tsx
- packages/dapp/src/components/listing/AppealChallengeRevealVote.tsx
- packages/dapp/src/components/listing/AppealResolve.tsx
- packages/dapp/src/components/listing/ListingPhaseActions.tsx
- allow council to input URL when granting appeal, put that URL in "read about decision" button
- not yet working when loading via graphql since query result doesn't contain data we need
> Granted Appeal URI

- packages/components/src/ListingHistoryEvent/EventDate.tsx
- make sure event date is always 148px wide so it doesn't get squished when rest of history event is bigger
- if there's a better way to do this, let me know
> Fix History Event Alignment

- packages/components/src/ListingSummary/ChallengeResults.tsx
- don't show challenge results on ready-to-update newsroom if there is no challenge
> Tiny Listing Card Fix

- packages/components/src/ListingDetailHeader/ListingDetailHeaderStyledComponents.tsx
- packages/components/src/ListingSummary/styledComponents.tsx
- use contain instead of cover for newsroom logo object-git
- set background to white
> Newsroom Listing Logo Fixes

- packages/components/src/Parameterizer/ChallengeProposalCommitVote.tsx
- packages/components/src/Parameterizer/ParameterizerStyledComponents.tsx
- packages/dapp/src/components/Parameterizer/ChallengeProposalCommitVote.tsx
- packages/dapp/src/components/Parameterizer/ChallengeProposalRevealVote.tsx
The pull request fixes the following issues with Parameterizer challenge voting
- User could not select a vote option when committing a vote
- The content at the bottom of the Challenge drawer would overflow outside the drawer boundary, if a user was viewing the dapp at a smaller desktop resolution
Issue: #909
> Parameterizer Voting bug fixes

- .circleci/config.yml
code coverage appears to have been broken for quite some time. this disables the nightly build, and will be enabled once coverage is fixed
> remove nightly build

- packages/components/src/ListingSummary/__snapshots__/ListingSummary.stories.storyshot
- packages/components/src/ListingSummary/styledComponents.tsx
- packages/dapp/src/components/listinglist/ListingListItem.tsx
- Only show 'prevChallenge' data for Rejected listing cards on the Registry page (#940)
- Set height for newsroom info on listing cards for the Registry page, so that approved listing cards all render at the same height (#914)
> Minor UI updates for Registry page

- packages/dapp/src/App.tsx
This update injects global styles for Dapp that properly sets default colors for link elements as well as the correct default sans-serif font, per Design.
> Fix default link colors for the Dapp

- packages/dapp/src/components/Main.tsx
- this is a bit hacky, but the account is not yet reflected in redux when the 2nd call to the function is made, so it makes the subscription twice
> prevent double user challenge data subscriptions

- packages/core/package.json
- packages/core/src/content/ipfsprovider.ts
- packages/core/src/contracts/tcr/civilTCR.ts
- packages/core/src/contracts/tcr/parameterizer.ts
- packages/core/src/globals.d.ts
- packages/core/src/types.ts
- packages/dapp/src/helpers/listingEvents.ts
- packages/utils/src/civilHelpers.ts
- yarn.lock
- still room for improvement in getting user challenge data, specifically getting rid of the `getRevealEvent` call and `getRewardClaimed` call. Would need to split up getting user challenge data though and update it in steps 
- update genesis block for rinkeby
- ignore first commit, part of another PR... sorry...
> reduce filtered log requests

- packages/components/package.json
- packages/dapp/src/components/ContractAddresses.tsx
- packages/dapp/src/components/Dashboard/Dashboard.tsx
- packages/dapp/src/components/Main.tsx
- packages/dapp/src/components/Parameterizer/index.tsx
- packages/dapp/src/components/Tokens/Tokens.tsx
- packages/dapp/src/components/listing/ListingRedux.tsx
- packages/dapp/src/components/listinglist/Listings.tsx
- packages/dapp/src/components/listinglist/ListingsInProgress.tsx
This PR includes:
- Updates `react-router-dom` version for `@joincivil/components` to match the version used in the dapp
- Adds router redirects for various URLs so that the URL matches the default renders for those views
- Uses `title` prop for `Helmet` component, instead of putting a the `<title>`
element inside the component, which can cause a `RangeError` related to Helmet's user of `deep-equal`. More details about this bug can be found here: https://github.com/nfl/react-helmet/issues/373
> Clean up routing for Dapp + GA, plus additional bug fixes

- packages/dapp/src/components/SignUpNewsroom.tsx
- packages/newsroom-signup/src/Newsroom.tsx
- packages/newsroom-signup/src/NewsroomProfile/CharterQuestions.tsx
- packages/newsroom-signup/src/NewsroomProfile/SignConstitution.tsx
Also, unrelated, but `handleTransactionError` was being called with no error from sign constitution button, so this handles that case without breaking as much.
> Don't pop up ethereum enable during email auth

- packages/components/src/Account/Auth/EmailAuth.tsx
- packages/components/src/Account/Auth/__snapshots__/EmailAuth.stories.storyshot
- packages/components/src/Button.tsx
- packages/components/src/input/Checkbox.tsx
- packages/components/src/input/__snapshots__/checkbox.stories.storyshot
- packages/components/src/input/checkbox.stories.tsx
- packages/newsroom-signup/src/NewsroomProfile/GrantApplication.tsx
- packages/newsroom-signup/src/NewsroomProfile/SignConstitution.tsx
Using `<label for="...">` instead of wrapping checkbox+text in `<label>` because our custom `Checkbox` component uses a wrapping `<label>` element to create custom checkbox design. Multiple labels for the same input are fine, but browser interpretations of multiple nested `<label>` elements is inconsistent (in some cases clicks on outer label don't transfer to input in inner label).
> Signup/login with enter key + clickable checkbox labels

- packages/components/src/ListingDetailPhaseCard/ChallengeCommitVoteCard.tsx
- packages/components/src/ListingDetailPhaseCard/ChallengeRequestAppealCard.tsx
- packages/components/src/ListingDetailPhaseCard/textComponents.tsx
- packages/components/src/NavBar/NavMenu.tsx
- packages/components/src/NavBar/__snapshots__/NavBar.stories.storyshot
- packages/components/src/NavBar/textComponents.tsx
- packages/components/src/Tokens/TokensTextComponents.tsx
This PR includes the following updates:
- Fixes for "NaN" durations in some listing detail phase card tooltips (#953)
- Adds "Registry Home" to the Registry dropdown in the top nav (#1065)
- Fixes "effecting" typo
> Misc UI updates and fixes for the dapp

- packages/components/src/NavBar/NavBar.tsx
- packages/components/src/NavBar/NavDrawer.tsx
- packages/components/src/NavBar/UserAccount.tsx
This PR fixes the issue where the drawer could not be closed via the "toggle" control, once it was opened. 
Issue #1071 
To fix this issue, this update refactors the `NavDrawer` and `UserAccount` components so the drawer lives inside the User Account component (which toggles the display of the drawer).  The User Account component now passes its `ref` to the child drawer. Finally, the drawer checks if the `event.target` for the "close the drawer on outside click" handler is either the toggle element or the drawer before triggering the "outside click" handler.
> Fix behavior of "toggle" element for user drawer

- packages/dapp/src/components/SignUpNewsroom.tsx
- packages/newsroom-signup/src/DataWrapper.tsx
- packages/newsroom-signup/src/Newsroom.tsx
- packages/newsroom-signup/src/NewsroomProfile/ApplicationSoFarPage.tsx
- packages/newsroom-signup/src/NewsroomProfile/index.tsx
- packages/newsroom-signup/src/SmartContract/UnderstandingEth.tsx
- packages/newsroom-signup/src/SmartContract/index.tsx
- Step stuff
- Lift step state up to parent `<Newsroom>` manager component
- Single step # for all sections, defined by enums
- Support for navigating across sections
- Auto-advance past grant step when grant approved/rejected or if user is on deprecated "waiting after skip" state
- Misc updates/fixes
@am9u @sruddy tagging for visibility if you if you want to integrate your stuff into step flow, but also very happy do the merge and hook up your components into this flow whenever they're ready
> Refactor step storage/navigation + grant approval/rejection [CIVIL-408] [CIVIL-486]

- packages/components/src/Tokens/buy/AirswapBuyCVL.tsx
doesn't appear to be working properly - the value is prepopulating correctly, but when you actually get the quote it returns an insane amount
> don't prepopulate airswap amount

- packages/components/src/TransactionButton.tsx
- packages/dapp/src/redux/analytics.ts
- packages/newsroom-signup/package.json
- packages/newsroom-signup/src/Newsroom.tsx
- packages/newsroom-signup/src/NewsroomProfile/GrantApplication.tsx
- packages/newsroom-signup/src/SmartContract/CreateNewsroomContract.tsx
- packages/newsroom-signup/src/actionCreators.ts
- packages/newsroom-signup/src/analytics.ts
- packages/newsroom-signup/src/index.ts
- packages/newsroom-signup/src/reducers.ts
This tracks step movement as pageviews, and has events for newly reaching a further step, as well as grant apply/skip and contract creation TXs.
Events and actions are set up for tracking other TXs (tokens, applying) and charter publish, but adding them all in was dragging on so I will do the rest after launch.
> Newsroom signup GA integration [CIVIL-477]

- packages/dapp/src/components/utility/TransactionStatusModalsHOC.tsx
Say that the posting to IPFS will take "moments" instead of "minutes" per suggestion from @nickreynolds
> Update copy for IPFS progress modal

- packages/newsroom-signup/src/ApplyToTCR/TransferToMultisig.tsx
Seemed like a good idea but it's buggy so reverting it - better a flash of a success modal than missing the multisig balance rehydration.
> Revert post token transfer modal flash fix

- .circleci/config.yml
In our k8s config, it uses `dapp:master` as the default image to use when the dapp pod starts up.  In the event that the pod gets killed outside of our CircleCI deploy, this seems to be the reason why our test env returns to that master image. 
This creates an image based on the branch name, but also on a general `test` name.  This is so we can key off the `test` tag in k8s to ensure when those start up, they use the last `test` image.
> Fix for Test Env Starting Up with Master

- .circleci/config.yml
- Dockerfile-dapp
the last PR I sent didn't actually work as intended - it set the build version in the `yarn build`, but not in the `docker` process that actually builds the container. This one should do the trick
> build version needs to be set in docker

- packages/dapp/src/components/Dashboard/ChallengeSummary.tsx
- packages/dapp/src/components/listing/Challenge.tsx
- Fix bug where Appeal Summary component would render in the My Tasks Dashboard tab for challenges that are awaiting appeal request (#1209 
- Fix link back to Listing Detail page from Historical Challenge page (#1206)
> Fixes for some Challenge / Voting related issues

- packages/components/src/Tokens/buy/UniswapBuy.tsx
- packages/dapp/src/components/Auth/AuthLogout.tsx
- packages/dapp/src/components/Auth/index.tsx
This isn't actually accessible except via URL, but can at least serve as a stop gap if people ask about it. That being said, we should do this properly in an upcoming sprint.
note: this also fixes an error I was seeing with the uniswap buy screen complaining that isMounted has no setter - I think react was setting this properly under the hood.
> add logout route

- packages/components/src/ApplicationPhaseStatusLabels.stories.tsx
- packages/components/src/ApplicationPhaseStatusLabels.tsx
- packages/components/src/ListingDetailHeader/ListingDetailHeader.tsx
- packages/components/src/ListingSummary/ListingPhaseLabel.tsx
- packages/components/src/ListingSummary/types.ts
- packages/components/src/__snapshots__/ApplicationPhaseStatusLabels.stories.storyshot
Issue #1216 
This update also DRYs up the rendering of these labels a bit, as well as adds the missing 'Awaiting Request to Appeal' label to the Listing Detail page header.
> Fix 'Awaiting Request to Appeal label in the Dapp

- packages/newsroom-signup/src/Newsroom.tsx
- packages/newsroom-signup/src/NewsroomProfile/index.tsx
- packages/newsroom-signup/src/SmartContract/index.tsx
- packages/newsroom-signup/src/actionCreators.ts
- packages/newsroom-signup/src/analytics.ts
- packages/newsroom-signup/src/constants.ts
We've had a lot of support tickets about people stuck on the "waiting on grant" step. Some of these were from foundation not actually using the link that sets the "grant approved" flag in DB, but we've gotten at least two users for whom the flag is set correctly but they're still stuck. To combat this and track it down:
- Refactor "waiting on grant" logic to be simpler and more centralized
- Act as if grant was approved if the user has enough CVL to apply (most likely because they received grant)
- Add some GA events to help debug
- Also, replaces solo "continue" button on Smart Contract step with the same back/next buttons as every other step, since people are getting lost navigating and this could help a little
> Improvements to handling post-grant transition [CIVIL-582]

- packages/newsroom-signup/src/Newsroom.tsx
- packages/newsroom-signup/src/NewsroomProfile/index.tsx
Buggy logic was "skip the grant step if the user is not waiting for grant approval", but new users who haven't even selected whether they
want to apply for grant approval or not are of course "not waiting for grant approval" so we erroneously skipped that step for them.
Similar logic is (correctly) used elsewhere so I've codified this into a dedicated variable `completedGrantFlow` to make it clearer.
> Fix buggy logic for when to skip grant step [CIVIL-751]

- packages/components/src/DAppMessageContent/styledComponents.tsx
- packages/dapp/src/components/listing/ChallengeDetail.tsx
- Check if user's EthAddress is available before requesting user challenge data from GraphQL
- Fix nested `<p>` elements issue with DApp Error Message component
> Fix issue where user w/ locked/not installed MetaMask sees incorrect UI based on user challenge data

- packages/ethapi/src/providerbackport.ts
Check if websocket connection is open via the websocket's `readyState` property, before calling `send` on the connection
https://civilmedia.atlassian.net/browse/CIVIL-568
> Fix `Parameterizer: InternalError: too much recursion` issue

- packages/components/src/ApplicationPhaseStatusLabels.tsx
- packages/components/src/ListingSummary/AppealJudgementBanner.tsx
- packages/components/src/ListingSummary/ListingSummaryRejected.tsx
- packages/components/src/ListingSummary/ListingSummaryUnderChallenge.tsx
- packages/components/src/ListingSummary/types.ts
- packages/components/src/__snapshots__/ApplicationPhaseStatusLabels.stories.storyshot
- packages/dapp/src/components/listinglist/ListingListItem.tsx
- packages/dapp/src/components/utility/HigherOrderComponents.tsx
- packages/dapp/src/helpers/transforms.ts
- packages/dapp/src/selectors/index.ts
- Fix issue where in commit/reveal phase displayed "Appeal Requested" banner on Registry Homepage when Web3 is enabled
- Fix appeal banner on summary cards on Registry Homepage to properly support
awaiting appeal judgement status
- Update text for awaiting appeal judgement status banner on summary
cards and application status label
> Various Appeal related UI fixes for the DApp

- packages/dapp/src/components/listing/AppealResolve.tsx
- packages/dapp/src/components/listing/AppealSubmitChallenge.tsx
- Add missing `appealGrantedStatementURI` prop to Submit Appeal Challenge card
- Minor code cleanup
> Fix missing Appeal Granted URL on Submit Appeal Challenge ballot card

- packages/components/src/ListingDetailPhaseCard/AppealChallengeCommitVoteCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealChallengeResolveCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealChallengeRevealVoteCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealDecisionCard.tsx
- packages/components/src/ListingDetailPhaseCard/AppealDecisionDetail.tsx
- packages/components/src/ListingDetailPhaseCard/AppealResolveCard.tsx
- packages/dapp/src/helpers/queryTransformations.ts
- Fix case issue with `appealGrantedStatementURI` prop
- Fix issue where GraphQL response transform function was setting the wrong value for `appeealGrantedStatementUri`
> Additional update to fix broken Appeal Granted Statement URL

- packages/components/src/imageUrls.ts
- packages/components/src/styleConstants.ts
- packages/dapp/src/components/Boosts/BoostCreate.tsx
- packages/dapp/src/components/Dashboard/ActivityListItem.tsx
- packages/dapp/src/components/Main.tsx
- packages/dapp/src/constants.ts
A lot of boilerplate here to get user's newsroom and newsroom data and charter data but I don't think there's any more concise way to do it without abstracting some HOC or something.
@sruddy not sure if you've worked on fetching newsroom data for standalone boost page but it'll probably look something like this but getting newsroom address from channel ID instead of `currentUserNewsrooms`.
> Standalone create boost page [CIVIL-793]

- packages/dapp/package.json
- packages/dapp/src/helpers/queryTransformations.ts
- yarn.lock
@am9u when you get a chance could you confirm that `yarn install` from this branch now works for you without ignore scripts (and without having civil-sdk linked)? Thanks!
> Bump civil-sdk to 1.8.5 [CIVIL-803]

- packages/components/package.json
- packages/components/src/HelmetHelper.tsx
- packages/components/src/index.ts
- packages/components/src/types.d.ts
- yarn.lock
Right now just using these for boosts, but would be good to update our use of `Helmet` elsewhere in the dapp at some point to add images and descriptions. Example invocation: https://github.com/joincivil/civil-sdk/blob/35ed473ced5c7de2d06a08d081d8b136130af19d/src/react/boosts/BoostCard.tsx#L42-L51
> Create HelmetHelper component for easier og meta and fb/twitter cards

- packages/dapp/src/components/listing/ListingBoosts.tsx
- packages/dapp/src/components/listing/ListingRedux.tsx
- packages/dapp/src/components/listing/styledComponents.tsx
I added a feature flag to the boost but I can't add it to the tab without breaking tabs. If we don't want Boost in the tab with a coming soon message we can wait on this.
> Adds Boost to listings tab

- packages/core/src/civil.ts
- packages/core/src/contracts/tcr/cvltoken.ts
- packages/dapp/src/apis/civilTCR.ts
- packages/dapp/src/components/listing/ListingOwnerActions.tsx
- update listing owner actions so exit listing also withdraws tokens to user wallet after exiting listing transaction
- updates needed to `ownerAddresses` in graphql newsroom query (otherwise need to disable graphql to see owner actions)
> exit listing

- packages/components/src/ListingDetailPhaseCard/WithdrawnCard.tsx
- packages/components/src/ListingDetailPhaseCard/index.ts
- packages/components/src/ListingDetailPhaseCard/textComponents.tsx
- packages/components/src/ListingHistoryEvent/constants.ts
- packages/core/src/types.ts
- packages/dapp/src/components/listing/ListingOwnerActions.tsx
- packages/dapp/src/components/listing/ListingPhaseActions.tsx
- packages/dapp/src/components/listing/ListingRedux.tsx
- packages/dapp/src/helpers/queryTransformations.ts
- better transaction modals
- better rendering of withdrawn listing
part of this is kind of hacky because of handling both graphql and web3 loading. I decided to just only care about rendering it correctly with graphql since we're trying to deprecate web3 loading anyways and it would've been too complicated
> exit listing improvements

- packages/core/src/contracts/newsroom.ts
- packages/core/src/types.ts
- packages/dapp/src/components/listing/ListingOwnerActions.tsx
- packages/dapp/src/components/listing/ListingPhaseActions.tsx
- packages/dapp/src/components/listing/ListingRedux.tsx
Separate exit listing & withdraw into 2 buttons. fix withdraw transaction to use newsroom owner instead of listing owner since listing owner is zeroed out once first transaction completes
> fix withdraw tokens owner action

- packages/dapp/package.json
- packages/dapp/src/components/Dashboard/ChannelAdmin/ChannelAdminPage.tsx
- packages/dapp/src/components/Dashboard/ChannelAdmin/newsroom/ManageNewsroom.tsx
- packages/dapp/src/components/Dashboard/ChannelAdminList/index.tsx
- packages/dapp/src/components/Dashboard/NewsroomsList.tsx
- packages/dapp/src/components/Main.tsx
- packages/dapp/src/constants.ts
- yarn.lock
the UI for this can more or less be ignored, this is to just make every we have everything we need in graphql to create a boost from a channel that was created via fast-pass. Toby and I will work together to get this page fleshed out before we turn the feature flag on.
> channel page

- packages/components/src/LoadingIndicator.tsx
- packages/components/src/Tabs/Tabs.tsx
- packages/components/src/__snapshots__/LoadingIndicator.stories.storyshot
- packages/components/src/__snapshots__/LoadingMessage.stories.storyshot
- packages/components/src/input/ImageFileToDataUri.tsx
- packages/dapp/.env
- packages/dapp/src/components/Boosts/BoostFeed.tsx
- packages/dapp/src/components/Dashboard/ChannelAdmin/newsroom/ManageNewsroom.tsx
- packages/newsroom-signup/src/ApplyToTCR/index.tsx
- packages/newsroom-signup/src/Newsroom.tsx
- packages/newsroom-signup/src/NewsroomManager/index.tsx
- packages/newsroom-signup/src/NewsroomProfile/AddRosterMembers.tsx
- packages/newsroom-signup/src/NewsroomProfile/ApplicationSoFarPage.tsx
- packages/newsroom-signup/src/NewsroomProfile/CharterQuestions.tsx
- packages/newsroom-signup/src/NewsroomProfile/NewsroomBio.tsx
- packages/newsroom-signup/src/NewsroomProfile/RosterMember.tsx
- packages/newsroom-signup/src/NewsroomProfile/index.tsx
- packages/newsroom-signup/src/RepublishCharterNotice.tsx
- packages/newsroom-signup/src/SmartContract/index.tsx
- packages/newsroom-signup/src/index.ts
- packages/newsroom-signup/src/styledComponents.tsx
- Reuses `newsroom-signup` components in new "manage newsroom" page, reworking them with copy/design updates to support this new context
- Misc `newsroom-signup` updates and improvements
- Designs are in flux, this is a barebones version. It's clean and nothing looks broken, but it doesn't match the designs.
- UI is behind `newsroom-channels` flag for now.
> Newsroom Manager update charter UI [CIVIL-994]

- packages/dapp/src/components/Dashboard/NewsroomsListItemComponent.tsx
Otherwise we have a flow where you try to create a boost, it says "your newsroom isn't whitelisted, check your stats on your dashboard page" and on the dashboard it just says "ready to update" and you're left hanging there.
> Tell newsroom officer what to do with "Ready to Update"

- packages/components/src/WithNewsroomChannelHOC.tsx
- packages/dapp/src/components/Boosts/BoostCreate.tsx
- packages/dapp/src/components/Dashboard/ManageNewsroom/WithNewsroomChannelAdminList.tsx
Without this, Launch Boost from nav is broken, so I think we need to deploy this to prod before we have anyone else use boosts (otherwise we'd have to make sure to direct them to launch boost via dashboard).
> Support newsroom channels from Launch Boost nav dropdown [CIVIL-1022]

- .circleci/config.yml
- .releaserc
- package.json
- packages/dapp/package.json
- packages/sdk/.releaserc
- packages/utils/test/salt.ts
- yarn.lock
this doesn't actually move civil-sdk into the monorepo yet, but just does an npm release. I think a lot of the packages are going to complain once they need a release that the tag already exists - the fix would be to just put a commit that bumps the version. I will run through all of them once I get a sdk set up properly
this also moves test/lint into the "build" job. I noticed that a bunch of time in CI is step in between job steps, and persisting workspaces. Combining them cut ~3 minutes off of the build.
> release sdk

- packages/newsroom-signup/src/ApplyToTCR/index.tsx
this was the old bignumber.js api and should be using bn.js
this didn't get caught since it the type was "any".
> fix(newsroom-signup): greatThanOrEqualTo should be gte

- packages/components/src/CurrencyConverter/UsdEthConverter.tsx
the token storefront is currently broken, and I suspect it is a result of this commit:
https://github.com/joincivil/Civil/commit/17a4547a151bb42fc81a9d2d712a172682dc8354#diff-723fb43d508074f47fb5a75cb7711617
Removing the default value fixes it, although I am unsure if this has any repercussions to anything Boost related.
> fix(components): no default value for CurrencyConverter

- packages/components/src/Account/Auth/AuthStyledComponents.tsx
- packages/components/src/Account/Auth/__snapshots__/EthAuth.stories.storyshot
- packages/components/src/Account/Auth/__snapshots__/VerifyToken.stories.storyshot
- packages/components/src/BrowserCompatible/BrowserCompatible.tsx
- packages/components/src/BrowserCompatible/__snapshots__/BrowserCompatible.stories.storyshot
- packages/components/src/DAppMessageContent/WrongNetwork.tsx
- packages/components/src/Hero/Hero.stories.tsx
- packages/components/src/Hero/__snapshots__/Hero.stories.storyshot
- packages/components/src/ListingDetailHeader/ListingDetailHeader.tsx
- packages/components/src/ListingSummary/NewsroomInfo.tsx
- packages/components/src/MetaMaskModal.tsx
- packages/components/src/TCRUserDashboard/DashboardActivityItem.tsx
- packages/components/src/TCRUserDashboard/DashboardActivityItemTask.tsx
- packages/components/src/TCRUserDashboard/DashboardNewsroomStripeConnect.tsx
- packages/components/src/Tokens/TokensAccountFaq.tsx
- packages/components/src/WalletOnboarding.tsx
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.connected.stories.storyshot
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.disabled.stories.storyshot
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.locked.stories.storyshot
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.mismatch.stories.storyshot
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.network.stories.storyshot
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.provider.stories.storyshot
- packages/components/src/WalletOnboardingV2/__snapshots__/WalletOnboardingV2.save.stories.storyshot
- packages/components/src/__snapshots__/Button.stories.storyshot
- packages/components/src/__snapshots__/WalletOnboarding.stories.storyshot
- packages/components/src/icons/MetaMaskIcons.tsx
- packages/components/src/icons/__snapshots__/icon.stories.storyshot
- packages/components/src/imageUrls.ts
I broke this in the last commit by turning on es6ModuleInterop in order to get web3 library to load. This commit changes it so png imports use the default import https://github.com/joincivil/Civil/commit/24766289f7e80b06e6b650648a9788cbb3999168#diff-52424fbfcf31b62270d93d195c7fd19cR8
> fix(components): use default import for png

- packages/components/src/TCRUserDashboard/DashboardNewsroom.tsx
- packages/dapp/src/components/Dashboard/NewsroomsListItemComponent.tsx
- packages/sdk/src/react/NewsroomWithdraw.tsx
- packages/sdk/src/react/boosts/Boost.tsx
- packages/sdk/src/react/boosts/BoostProceeds.tsx
- packages/sdk/src/react/boosts/BoostStyledComponents.tsx
- packages/sdk/src/react/boosts/queries.ts
- packages/sdk/src/react/urlConstants.ts
- packages/utils/src/urlConstants.ts
Shows ETH and USD proceeds for a newsroom both on the My Newsrooms dashboard and on the Boost permalink page (if you're an admin for that newsroom).
> feat: boost proceeds [CIVIL-1017]

- packages/dapp/src/components/Main.tsx
- packages/dapp/src/registry/RegistryApp.tsx
- packages/dapp/src/registry/RegistrySection.tsx
- packages/dapp/src/registry/RegistryWrapper.tsx
Refactors a bit to create yet another dapp wrapper component. Moved a bunch of the logic from `RegistrySection` out into `RegistryWrapper`, in order to cleanly use dispatch and context in `RegistrySection` to instantiate the fire analytics event early enough that the boost embed can share that logic.
Look at https://github.com/joincivil/Civil/pull/1429 first.
> feat(dapp): support analytics event in boost embed [CIVIL-1035]

- packages/dapp/src/components/Main.tsx
- packages/dapp/src/constants.ts
- packages/dapp/src/registry/RegistryApp.tsx
- packages/dapp/src/registry/RegistrySection.tsx
- packages/dapp/src/registry/RegistryWrapper.tsx
A bit hacky because boost embed should go inside `RegistrySection` (it reuses no less than 6 of the registry wrapper components) BUT if we are on the boost embed then we don't want to show the fallback `RegistryShell` nav bar (and whatever else that contains in the future) while it's loading.
It's a small hack, but open to any other ideas about how to do this or how to make more explicit.
> fix(dapp): add boost embed back in refactored dapp architecture

- packages/components/src/BrowserCompatible/__snapshots__/BrowserCompatible.stories.storyshot
- packages/components/src/CurrencyConverter/__snapshots__/CurrencyConverter.stories.storyshot
- packages/components/src/EthAddressViewer/__snapshots__/EthAddressViewer.stories.storyshot
- packages/components/src/Hero/__snapshots__/Hero.stories.storyshot
- packages/components/src/ListingDetailHeader/__snapshots__/ListingDetailHeader.stories.storyshot
- packages/components/src/ListingSummary/__snapshots__/ListingSummary.stories.storyshot
- packages/components/src/NavBar/__snapshots__/NavBar.stories.storyshot
- packages/components/src/Table/__snapshots__/Table.stories.storyshot
- packages/components/src/Tabs/__snapshots__/Tabs.stories.storyshot
- packages/components/src/Tokens/__snapshots__/TokensAccount.stories.storyshot
- packages/components/src/Tokens/buy/__snapshots__/TokensTabBuy.stories.storyshot
- packages/components/src/__snapshots__/ModalContent.stories.storyshot
- packages/components/src/context/CivilContext.ts
- packages/components/src/input/__snapshots__/Input.stories.storyshot
- packages/elements/src/containers/mediaQueries.ts
- packages/sdk/package.json
- packages/sdk/src/react/boosts/BoostCard.tsx
- packages/sdk/src/react/boosts/BoostLoader.tsx
- packages/sdk/src/react/boosts/BoostNewsroom.tsx
- packages/sdk/src/react/boosts/BoostShare.tsx
- packages/sdk/src/react/boosts/BoostShareEmbed.tsx
- packages/sdk/src/react/boosts/BoostStyledComponents.tsx
Adds `renderContext` attribute to `CivilContext` which can be (currently) set to `DAPP` (default) or `EMBED` so that we can conditionally render some Boost stuff based on that context. Also adds that value in `styled-components` theme
Style updates:
- Disable input field when boost is ended
- Prevent scrolling in embed + show fading-out "view boost" link
- Add border to embed
- Link boost newsroom name to newsroom
- Better responsiveness for boost share widget
- Hide "visit newsroom" link on embed
- Truncate boost title length in embed
> Boost embed style updates [CIVIL-1079] [CIVIL-1031]

- packages/dapp/src/constants.ts
- packages/dapp/src/embeds/BoostLoader.tsx
- packages/dapp/src/embeds/EmbedsApp.tsx
Dumping my notes/slack convo about this issue for posterity, but the TL;DR is just to read the code.
according to react-redux ConnectedRouter docs, if you use it you have to remove any use of BrowserRouter or else there will be these problems syncing route state. this wasn't an issue before but with upgrade from react-router v4 to v5 it's now an issue: boost embed component doesn't receive updates when route changes and no use of useParams or withRouter anywhere in the component tree works.
so one fix that works is to replace the top level BrowserRouter with ConnectedRouter, which only works when wrapped in redux Provider, so we have to lift that too, and all the redux store code, which shouldn't need much, but in practice at the moment it ends up bringing in the whole codebase and borks …
> fix(dapp): workaround to fix payment route in boost embed [CIVIL-1107]

- packages/dapp/src/components/providers/AnalyticsProvider.tsx
- packages/dapp/src/components/providers/AppProvider.tsx
- packages/dapp/src/registry/RegistryApp.tsx
Moves analytics event setup into AppProvider, via new AnalyticsProvider, so that embeds can use. This was done in a clunky way in #1430 but was removed by refactor in #1432, but the refactor supports a simpler way to implement it.
> fix(dapp): set up analytics in AppProvider so boost embed can use again

- packages/dapp/src/embeds/BoostLoader.tsx
- packages/sdk/src/react/boosts/Boost.tsx
- packages/sdk/src/react/boosts/BoostPermissionsHOC.tsx
- packages/sdk/src/react/boosts/payments/BoostPayEth.tsx
- packages/sdk/src/react/boosts/payments/BoostPayOptions.tsx
- packages/sdk/src/react/boosts/payments/BoostPayments.stories.tsx
- packages/sdk/src/react/boosts/payments/BoostPayments.tsx
In the dapp registry app we call this from the global nav, wasn't getting called properly here. Also with this update, ethereum enable will only be called from embed once the user enters the payment flow.
> fix(sdk): get web3 working in boost embed [CIVIL-1107]

- packages/components/src/Account/Auth/EthAuth.tsx
- packages/components/src/ChevronAnchor.tsx
- packages/components/src/MetaMaskModal.tsx
- packages/components/src/TransactionButton.tsx
- packages/core/src/contracts/newsroom.ts
- packages/dapp/src/components/Dashboard/NewsroomsListItemComponent.tsx
- packages/dapp/src/components/utility/TransactionStatusModalsHOC.tsx
- packages/newsroom-manager/src/CompleteYourProfile.tsx
- packages/newsroom-manager/src/NameAndAddress.tsx
- packages/newsroom-manager/src/NewsroomUser.tsx
- packages/newsroom-manager/src/SignConstitution.tsx
- packages/newsroom-signup/src/NewsroomProfile/SignConstitution.tsx
- packages/newsroom-signup/src/NewsroomUser.tsx
- packages/newsroom-signup/src/RepublishCharterNotice.tsx
- packages/newsroom-signup/src/SmartContract/AddMember.tsx
- packages/newsroom-signup/src/SmartContract/CreateNewsroomContract.tsx
- packages/newsroom-signup/src/TransactionStatusModalsHOC.tsx
Fixes the two issues affecting republish charter:
1. `newsroom.updateRevisionURIAndHash` passed default `signature` argument to web3 call as `""` which errored on "invalid bytes value" - `"0x"` instead fixed that.
2. Sometimes IPFS charter publish times out, but there's no feedback so UI just hangs. This catches IPFS (also any web3) errors and displays an error modal.
Also some other misc fixes.
> Fixes and improvements for republish charter flow

- packages/dapp/src/components/header/styledComponents.tsx
Mobile header used to be 54px high, was changed recently to be taller and so it overlapped the top of page content. Could move all the page content down but it looked fine making the header 54px again, with a couple tweaks.
> style(dapp): restore slim mobile header

- packages/sdk/src/react/boosts/BoostFeed.tsx
Issue: Page crashes if there is a channel associated with a newsroom that has not created a Boost.
> fix(dapp): listing page boost crashing

- packages/sdk/src/react/boosts/BoostStyledComponents.tsx
- packages/sdk/src/react/boosts/payments/BoostPayEth.tsx
The error was kind of dumb and unrelated to my investigations.
Previously this only checked wallet in componentDidUpdate transition from not selected (i.e. choosing between when eth and credit card options) to selected. If stripe isn't enabled for a boost, component mounts with eth option already selected so it wasn't getting called.
Also has tiny mobile responsive css fix.
> fix(sdk): call eth check even if boost eth pay is mounted selected [CIVIL-1142]

- packages/newsroom-signup/src/reducers.ts
`NewsroomsListItemComponent` would hydrate newsroom multisig balance whenever its `newsroom` prop from redux was updated. However, checking/dispatching multisig balance would update newsroom state in redux (i.e. `state.set(address, { ...state.get(address), multisigBalance: newBalance })`. Redux connect does a shallow equality check and would see that its newsroom state appeared to have updated and would update `NewsroomsListItemComponent` which would check multisig balance again.
This was infinitely creating newsroom state objects, causing a memory leak either in redux or our code, I couldn't track it down.
This update makes the reducer a little smarter, and won't create a new newsroom state object unless the multisig address or balance has actually changed.
This is a pretty specific fix …
> fix: memory leak/infinite loop when checking newsroom multisig [CIVIL-1019]

- packages/components/src/ListingDetailPhaseCard/textComponents.tsx
- packages/sdk/src/react/boosts/BoostShare.tsx
- packages/sdk/src/react/boosts/BoostStyledComponents.tsx
- packages/sdk/src/react/boosts/payments/BoostPayOptions.tsx
- packages/sdk/src/react/boosts/payments/BoostPayStripe.tsx
- packages/sdk/src/react/boosts/payments/BoostPayments.tsx
Because of how usdToSpend is stored in history state it was slightly harder (or maybe I'm missing something) to do what story boost flow does and just update payment amount to $2 if they continue, so instead I added a link to go back and edit payment amount, which isn't as nice, but it's kind of an edge case, and we'll replace this flow at some point anyway.
> Min $2 for embedded project boost card payments + small tweaks

- packages/components/src/TCRUserDashboard/DashboardNewsroom.tsx
- packages/dapp/src/components/Dashboard/ActivityListItem.tsx
- packages/dapp/src/components/Dashboard/ManageNewsroom/ManageNewsroom.tsx
- packages/newsroom-signup/src/NewsroomManager/index.tsx
- packages/sdk/src/react/boosts/BoostForm.tsx
Rather than blocking access entire "Manage Newsroom" page if newsroom is under challenge, only the "Edit Charter" tab should be blocked.
> Move "under challenge" lock to Edit Charter tab [CIVIL-995]

- packages/sdk/package.json
- packages/sdk/src/react/NewsroomWithdraw.tsx
- packages/sdk/src/react/boosts/Boost.tsx
- packages/sdk/src/react/boosts/BoostForm.tsx
- packages/sdk/src/react/boosts/BoostNewsroom.tsx
- packages/sdk/src/react/boosts/BoostPermissionsHOC.tsx
- packages/sdk/src/react/boosts/BoostShareEmbed.tsx
- packages/sdk/src/react/boosts/payments/BoostPayEth.tsx
- yarn.lock
Primarily a refactor of `BoostPermissionsHOC` to use channel admin gql query to check whether user should have permission to edit a boost, instead of web3.
> Reduce unnecessary/premature kirby popups on Boosts [CIVIL-1134] [CIVIL-1186]

- packages/components/src/CurrencyConverter/CurrencyConverter.tsx
- packages/components/src/CurrencyConverter/UsdEthConverter.tsx
- packages/sdk/src/react/boosts/BoostStyledComponents.tsx
- packages/sdk/src/react/boosts/payments/BoostPayEth.tsx
Instead of popping up kirby selection as soon as you enter ETH payment flow.
> chore(sdk): "select wallet" button on project boost [CIVIL-1134]

- packages/sdk/src/react/boosts/payments/BoostPayFormEth.tsx
- no longer need to check window.ethereum when sending payment
> fix: incognito portis boost payments

- packages/dapp/src/components/header/styledComponents.tsx
Had these sitting on my machine from the other day. Prevent button text wrapping on small screens and increasing header height, plus more space for usernames, etc.
> style(dapp): global nav mobile responsive tweaks

- packages/newsroom-signup/src/ApplyToTCR/index.tsx
- need to  improve messaging after apply since we no longer can access data the same way, but this prevents page from crashing
> fix: apply to newsroom no longer checks redux

- packages/dapp/devops/nginx.conf
- packages/dapp/src/App.tsx
- packages/dapp/src/components/Auth/index.tsx
- packages/dapp/src/components/Main.tsx
- packages/dapp/src/components/header/NavBar.tsx
- packages/dapp/src/components/header/UserAccountContainer.tsx
- packages/dapp/src/embeds/EmbedsApp.tsx
- packages/dapp/src/registry/LazyRegistryApp.tsx
change to nginx so that index.html is sent with no-cache headers. this is definitely less than ideal since it requires the initial page load to always come from origin, however it should fix the "chunk failed to load" in (most) scenarios. 
Longer term fix is to put this in front of an edge cache, but that requires some more doing. 
Also sneaking in webpack bundle names. Pleas use this for any async loaded components going forward.
> fix(dapp): don't cache index.html

- .circleci/config.yml
- package.json
- packages/sdk/package.json
This will make the standalone boost embed loader script available for newsrooms to embed from `registry.civil.co/loader/boost.js`.
It's clunky because it requires lifting information about dapp and sdk directory structure up into root package.json, but I don't see a way around that. I thought about putting this task inside dapp or sdk, bundling it with an existing build script, but this task will only work after _both_ of those packages have been built, so makes more sense for the root package.json to handle it.
I also can think of various ways to abstract multiple "loader" scripts to be served this way, but don't want to premature refactor until we see if/how we need to do something similar like this in the future, so I'm leaving it boost-specific for now.
Open to any other ways of …
> A way to serve boost embed loader script [CIVIL-1243]

- packages/components/src/Payments/Payments.tsx
- packages/components/src/Payments/PaymentsEth.tsx
- packages/components/src/StoryFeed/StoryFeedItem.tsx
- packages/components/src/TCRUserDashboard/Dashboard.tsx
- packages/components/src/TCRUserDashboard/DashboardUserInfoSummary.tsx
- packages/components/src/context/AuthService.ts
- packages/dapp/src/components/Dashboard/ClaimRewardsItem/ClaimRewardsItemWrapper.tsx
- packages/dapp/src/components/Dashboard/Dashboard.tsx
- packages/dapp/src/components/Dashboard/DashboardActivity.tsx
- packages/dapp/src/components/Dashboard/MyTasksItem/MyTasksItemWrapper.tsx
- packages/dapp/src/components/Dashboard/MyTasksProposalItem/MyTasksProposalItemWrapper.tsx
- packages/dapp/src/components/Dashboard/NewsroomsListItem.tsx
- packages/dapp/src/components/Dashboard/NewsroomsListItemComponent.tsx
- packages/dapp/src/components/Dashboard/RescueTokensItem/RescueTokensItemWrapper.tsx
- packages/dapp/src/components/StoryFeed/StoryFeed.tsx
- packages/dapp/src/components/Web3AuthWrapper.tsx
- packages/dapp/src/components/providers/AppProvider.tsx
- packages/dapp/src/embeds/StoryBoostLoader.tsx
- packages/dapp/src/helpers/queryTransformations.ts
- packages/dapp/src/registry/RegistryApp.tsx
- packages/sdk/src/react/StoryBoost/StoryBoost.tsx
- packages/sdk/src/react/StoryBoost/embed.tsx
Basically we need a way to launch login/signup flow (e.g. `dispatch(await showWeb3LoginModal())`) from outside of dapp package. This commit has dapp `Web3AuthWrapper` hook these functions into `CivilContext` via `AuthService` so that `Payments` component can call it itself.
Other stuff refactored to use context instead of passing down from story feed.
End result is that story boost embed gets all this stuff for free.
> Refactor auth modals into CivilContext and AppProvider to support login flow in story boost embed [CIVIL-1267]

- packages/dapp/src/components/Main.tsx
- packages/dapp/src/components/Web3AuthWrapper.tsx
- packages/dapp/src/components/providers/AppProvider.tsx
- packages/utils/src/apolloClient.ts
Moving some stuff from `Main` (dapp-only) to `Web3AuthWrapper` and `AppProvider` (both dapp and embeds). This fixes staging-only bug where if the embed is the first time you visit the dapp then the network value is set wrong, also fixes issues where iframes have isolated localStorage as Safari does.
Also updating logic so that gql endpoint depends on `config.DEFAULT_ETHEREUM_NETWORK` to begin with, but it won't overwrite network value set by web3 network being updated. (Though we still don't, I think, change the uri in already-created apollo client, but on page refresh the network value will take effect).
> Share network/gql logic between dapp and embeds [CIVIL-1283]

- packages/dapp/src/components/Dashboard/DashboardActivity.tsx
graphql complains if 2 fragments across app have same name
> chore: cleanup fragment name

- packages/newsroom-signup/src/ApplyToTCR/ApplyToTCRForm.tsx
Had this lying around on my computer, not sure if it really matters since I think no one will go all the way through this flow anymore, but it's a trivial update that is a bit better.
> With redux stuff removed, there's no feedback at all after applying to registry, it looks like you never did it. This way we can at least direct the user to the dashboard where they can see they've applied.
> Slightly better post-apply flow

- packages/components/src/TCRUserDashboard/DashboardNewsroom.tsx
- packages/sdk/src/react/boosts/BoostEmbedIframe.tsx
Minor stuff but useful to get out soon in case we send that email to newsrooms Friday.
Was testing on default WP theme which has an insane line height and embed looked terrible.
Also adds support email to error message (but more specific error messages based on the updates you made Nick are forthcoming).
> style(sdk): tweak embed styles + support email in error

- packages/dapp/src/components/Dashboard/ManageNewsroom/ManageNewsroom.tsx
- packages/newsroom-signup/src/NewsroomManager/ManageContractMembers.tsx
- packages/newsroom-signup/src/NewsroomManager/index.tsx
- packages/newsroom-signup/src/SmartContract/AddMember.tsx
- packages/newsroom-signup/src/SmartContract/AddMembersToContract.tsx
- packages/newsroom-signup/src/SmartContract/index.tsx
Adds a new "Smart Contract" tab in the `/manage-newsroom/<address>` manager, using a new `newsroom-signup` component `ManageContractMembers` that wraps the pre-existing smart contract member logic in a tidy way, hydrating various redux bits as necessary in this different context, and making sure changes are shared between this component and the post-apply charter editor one tab over since users may have to go back and forth between them (unfortunately, for now at least).
> Support adding users to smart contract from post-apply manager [CIVIL-1297]

- packages/dapp/src/components/Dashboard/ManageNewsroom/ManageNewsroom.tsx
- packages/newsroom-signup/src/NewsroomProfile/RosterMember.tsx
- packages/newsroom-signup/src/styledComponents.tsx
- packages/sdk/src/react/boosts/BoostPermissionsHOC.tsx
Whole Manage Newsroom page should be blocked if not `currentUserIsAdmin`, etc.
> fix: better permissions checks and UI for Manage Newsroom [CIVIL-918]

- packages/sdk/src/react/boosts/BoostEmbedIframe.tsx
Non `allow-forms` sandbox was preventing submission of username during embedded new user onboarding.
> Fix story boost embed onboarding [CIVIL-1457]

- packages/sdk/src/react/StoryBoost/embed.tsx
Prevent out of body boost experience as happening on Gotham Gazette. This check happens in embed loader, outside of embed iframe, and so won't blow up sentry.
> fix(sdk): don't load boost embed if it's not in <body>
