.circleci/config.yml, packages/dapp/src/components/Header.tsx
- fixing typo in circleci config
- fixing docker build command
- only build when master is updated
=> fixing circleCI

.circleci/config.yml
Additionally removed Slack flags as they do not work correctly
=> Moved CircleCI builds to persisted workflows

README.md, packages/core/README.md, packages/typescript-types/README.md, packages/typescript-types/package.json, packages/typescript-typings/README.md, packages/typescript-typings/package.json
- Fixed stuff concerning migrations
- Added info concerning types / typings packages
=> Updated readmes

packages/core/src/types.ts, packages/core/src/utils/web3wrapper.ts
This PR is basis for newsroom message signing, but putting it into smaller chunks for readabillity
=> Added ability to sign messages in web3wrapper

README.md
=> fixing npm badge links with dashes

.prettierignore, packages/contracts/package.json, packages/core/package.json, packages/dapp/package.json, packages/debug-ui/package.json, packages/editor/package.json, packages/utils/package.json
prettier was throwing errors on the readme file.  seems like we dont need it there
=> Ignore readmes

packages/dapp/src/apis/civilTCR.ts, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/ListingDetail.tsx
if it has passed the application stage without challenge
=> adding button to whitelist application

packages/contracts/contracts/interfaces/IGovernment.sol, packages/contracts/contracts/tcr/AddressRegistry.sol, packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/contracts/tcr/Government.sol, packages/contracts/test/tcr/government/get.ts, packages/contracts/test/tcr/government/setAppellate.ts, packages/contracts/test/tcr/registryWithAppeals/claimAppealChallengeReward.ts, packages/contracts/test/tcr/registryWithAppeals/claimReward.ts, packages/contracts/test/tcr/registryWithAppeals/isWhitelisted.ts
- PR already reviewed, but merged into wrong branch (https://github.com/joincivil/Civil/pull/118)
- going to merge if tests pass
=> fix resolve appeal challenge

packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/test/tcr/registry/hasClaimedTokens.ts, packages/contracts/test/tcr/registryWithAppeals/appealChallengeReward.ts, packages/contracts/test/tcr/registryWithAppeals/challenge.ts, packages/contracts/test/tcr/registryWithAppeals/claimReward.ts, packages/contracts/test/tcr/registryWithAppeals/hasClaimedChallengeAppealTokens.ts
- should increase code coverage a bit
- cleanup reward claiming, refactor appeal challenges to use same mapping as regular challenges
=> adding tests and refactoring CivilTCR to remove unnecessary check

packages/core/src/contracts/newsroom.ts, packages/core/src/contracts/utils/contracts.ts, packages/core/src/types.ts, packages/core/src/utils/listingDataHelpers/appealHelper.ts, packages/dapp/src/actionCreators/newsrooms.ts, packages/dapp/src/components/ListingList.tsx, packages/dapp/src/components/ListingListItem.tsx, packages/dapp/src/components/listing/Listing.tsx, packages/dapp/src/components/listing/ListingDetail.tsx, packages/dapp/src/helpers/listingEvents.ts, packages/dapp/src/reducers/index.ts, packages/dapp/src/reducers/newsrooms.ts, packages/utils/src/contracts.ts
- Adding newsroom data to redux so we can easily use it when rendering listings
- Might not be kicking off the API call to get newsroom data correctly
=> newsroom redux

packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/utils/listingDataHelpers/appealChallengeHelper.ts, packages/core/src/utils/listingDataHelpers/appealHelper.ts, packages/core/src/utils/listingDataHelpers/listingHelper.ts, packages/dapp/package.json, packages/dapp/src/components/listing/AppealDetail.tsx, packages/dapp/src/components/listing/Listing.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/ListingListItemOwner.tsx, packages/dapp/src/components/listinglist/ListingListItemStatus.tsx, packages/dapp/src/helpers/listingEvents.ts, packages/dapp/src/reducers/index.ts, packages/dapp/src/reducers/listings.ts, packages/dapp/src/typings.d.ts, yarn.lock
- Keeping listings up to date by re-adding them to redux after waiting for expiration timer. 
- Adding statuses to listing list item widget. 
- Fixing bugs in core around getting state.
=> Listing List Item Statuses, States Update Based on Timers

packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/ListingPhaseActions.tsx
This is a small update to make the user more aware of when phases are ending.
=> Add CountdownTimers for various Application/Challenge phases

packages/dapp/src/actionCreators/newsrooms.ts, packages/dapp/src/components/listinglist/ListingListItemStatus.tsx, packages/dapp/src/components/listinglist/Listings.tsx, packages/dapp/src/helpers/listingEvents.ts, packages/dapp/src/reducers/index.ts, packages/dapp/src/reducers/newsrooms.ts
- adding set of newsrooms current user is owner of to state
- adding tab to display this list
=> Current User's Newsrooms

packages/core/src/contracts/tcr/eip20.ts, packages/dapp/src/components/CreateNewsroom.tsx, packages/dapp/src/components/newsroom/NewsroomDetail.tsx, packages/dapp/src/components/newsroom/NewsroomManagement.tsx
Multisig TCR apply not there yet, but want to get some useful bits reviewed and out:
- Add option to create multisig newsroom
- Show multisig details in dapp
- Add ability to send CVL to multisig
- Misc UI fixes/updates
I'm newish to react so any feedback on react patterns/antipatterns are welcome too.
=> Helpers and UI updates for multisig newsrooms

packages/core/doc/examples/low-level/multisig.ts, packages/core/doc/examples/low-level/typed_contracts.ts, packages/core/package.json, packages/core/src/civil.ts, packages/core/src/utils/ethapi.ts, packages/dapp/src/actionCreators/userAccount.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/MyActivity.tsx, packages/dapp/src/components/navbar/NavBar.tsx, packages/dapp/src/helpers/civilInstance.ts, packages/dapp/src/helpers/listingEvents.ts, packages/dapp/src/reducers/challenges.ts, packages/dapp/src/reducers/index.ts, packages/utils/src/viewHelpers.ts, yarn.lock
- Adding polling for web3 account. 
- When account changes, get new balances and challenge data. 
- Updating redux stores to support data for different users.
=> user switching

packages/core/src/contracts/multisig/basemultisigproxy.ts, packages/core/src/utils/errors.ts, packages/dapp/src/apis/civilTCR.ts, packages/dapp/src/components/newsroom/NewsroomManagement.tsx
- Missing `await` made it seem like everything was multisig
- Quick check that there's enough token to apply
=> Couple multisig improvements

packages/contracts/contracts/tcr/AddressRegistry.sol, packages/contracts/contracts/tcr/CivilTCR.sol
- tiny refactor of TCR contracts to make AddressRegistry unaware of any concept of overturned challenges
=> Tiny TCR contract refactor

packages/dapp/src/actionCreators/listings.ts, packages/dapp/src/components/listing/Listing.tsx, packages/dapp/src/reducers/challenges.ts, packages/dapp/src/reducers/index.ts, packages/dapp/src/reducers/listings.ts
- using same pattern as loading challenge page to load listing if on listing page and listing data not present
=> Loading Listing Page

packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/types.ts, packages/dapp/src/apis/civilTCR.ts, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/ChallengeRewardsDetail.tsx, packages/dapp/src/components/newsroom/NewsroomDetail.tsx, packages/dapp/src/components/newsroom/NewsroomManagement.tsx, packages/utils/src/viewHelpers.ts
- Adding reward amount to challenge component (displays if user has collected reward)
- Bug fixes for approval function and token decimal conversion
=> vote reward history

packages/core/src/civil.ts, packages/core/src/contracts/tcr/appeal.ts, packages/dapp/src/components/Parameterizer.tsx, packages/dapp/src/components/listing/AppealChallengeDetail.tsx, packages/dapp/src/components/listing/AppealDetail.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx
- don't publish to event log by default (was introducing an extra transaction to challenges/applications)
- fixing data and formatting
=> Several minor fixes around challenges

packages/components/src/Button.stories.tsx, packages/components/src/Button.tsx, packages/components/src/PhaseCountdown/__snapshots__/PhaseCountdown.stories.storyshot, packages/components/src/StepProcess/__snapshots__/StepProcess.stories.storyshot, packages/components/src/TransactionButton.tsx, packages/components/src/__snapshots__/Button.stories.storyshot, packages/components/src/__snapshots__/Collapsable.stories.storyshot, packages/components/src/__snapshots__/DetailTransactionButton.stories.storyshot, packages/components/src/__snapshots__/Heading.stories.storyshot, packages/components/src/__snapshots__/LoadingIndicator.stories.storyshot, packages/components/src/__snapshots__/Message.stories.storyshot, packages/components/src/__snapshots__/Modal.stories.storyshot, packages/components/src/__snapshots__/ModalContent.stories.storyshot, packages/components/src/__snapshots__/SignConstitutionButton.stories.storyshot, packages/components/src/input/__snapshots__/Dropdown.stories.storyshot, packages/components/src/input/__snapshots__/Input.stories.storyshot
- Add DarkButton
- Add Inverted and Dark TransactionButton styles
- Add support for custom pre/post transtions AOP methods to
TransactionButton
=> Button / TransactionButton component style updates

packages/core/src/contracts/tcr/voting.ts, packages/dapp/src/actionCreators/userAccount.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/listing/AppealChallengeDetail.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/CommitVoteDetail.tsx, packages/dapp/src/components/navbar/NavBar.tsx
- get balance of tokens held in voting contract for user
- display in nav bar
- multiply token inputs by 1e18
=> voting balance

packages/core/doc/examples/low-level/multisig.ts, packages/core/doc/examples/low-level/typed_contracts.ts, packages/core/src/civil.ts, packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/utils/ethapi.ts, packages/dapp/src/actionCreators/network.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/Parameterizer.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/Listing.tsx, packages/dapp/src/components/listing/ListingHistory.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/Listings.tsx, packages/dapp/src/components/listinglist/ListingsInProgress.tsx, packages/dapp/src/components/listinglist/MyActivity.tsx, packages/dapp/src/components/navbar/NavBar.tsx, packages/dapp/src/components/parameterizer/Proposal.tsx, packages/dapp/src/components/parameterizer/Proposals.tsx, packages/dapp/src/reducers/index.ts, packages/dapp/src/reducers/network.ts
previous PR didn't actually get into master
=> network check 2

packages/components/src/ListingDetailPhaseCard/ChallengeRequestAppealCard.tsx, packages/components/src/ListingDetailPhaseCard/ChallengeResults.tsx, packages/components/src/ListingDetailPhaseCard/CommitVote.tsx, packages/components/src/ListingDetailPhaseCard/ListingDetailsPhaseCard.stories.tsx, packages/components/src/ListingDetailPhaseCard/RevealVote.tsx, packages/components/src/ListingDetailPhaseCard/index.ts, packages/components/src/__snapshots__/SignConstitutionButton.stories.storyshot, packages/dapp/src/components/listing/ChallengeDetail.tsx
- Fix the Request Appeal button to actually work
- Fix formatting of the Challenge Results graph (will be DRY-ing this up in an upcoming update)
- Update the Salt form inputs for Commit/Reveal vote to indicate that Salt should be a number
=> Bug fixes and improvements for DApp UI

packages/dapp/src/components/listing/Listing.tsx, packages/dapp/src/components/listing/ListingPhaseActions.tsx, packages/dapp/src/helpers/listingEvents.ts
- Fixing callbacks so listings re-render properly when changing state without event being fired. Adding expiry to some components' props so they re-render when it changes.
=> Fixing Challenge Stage Transitions

packages/core/src/contracts/tcr/eip20.ts, packages/core/src/contracts/tcr/voting.ts, packages/dapp/src/actionCreators/userAccount.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/helpers/tokenEvents.ts, packages/dapp/src/reducers/userAccount.ts
keeping token and voting rights balances up to date (by subscribing to events that change balance)
=> Token Balance Subscriptions

packages/core/src/content/ipfsprovider.ts, packages/core/src/contracts/newsroom.ts, packages/dapp/package.json, packages/dapp/src/components/listing/ListingDetail.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/newsroom/NewsroomManagement.tsx, packages/dapp/src/typings.d.ts, yarn.lock
* always pin content after adding it on IPFS
* display charter description on newsroom cards / listing detail page
* everything in the NewsroomManager component is placeholder, real version will go in NewsroomManagerV2
=> save and display charter v2

packages/core/src/contracts/tcr/civilTCR.ts, packages/dapp/src/actionCreators/challenges.ts, packages/dapp/src/components/listinglist/MyActivity.tsx, packages/dapp/src/helpers/listingEvents.ts, packages/dapp/src/reducers/challenges.ts, packages/dapp/src/reducers/index.ts
- Getting challenges started by user
- storing in redux, showing in my activity
=> User Challenges

packages/components/src/ListingDetailPhaseCard/AppealDecisionCard.tsx, packages/components/src/ListingDetailPhaseCard/index.ts, packages/components/src/ListingHistoryEvent/ApplicationEvent.tsx, packages/components/src/ListingHistoryEvent/ChallengeEvent.tsx, packages/components/src/ListingHistoryEvent/ChallengeFailedEvent.tsx, packages/components/src/ListingHistoryEvent/ChallengeSucceededEvent.tsx, packages/components/src/ListingHistoryEvent/EventDate.tsx, packages/components/src/ListingHistoryEvent/ListingHistoryEvent.stories.tsx, packages/components/src/ListingHistoryEvent/ListingHistoryEvent.tsx, packages/components/src/ListingHistoryEvent/RejectedEvent.tsx, packages/components/src/ListingHistoryEvent/WhitelistedEvent.tsx, packages/components/src/ListingHistoryEvent/__snapshots__/ListingHistoryEvent.stories.storyshot, packages/components/src/ListingHistoryEvent/constants.ts, packages/components/src/ListingHistoryEvent/index.tsx, packages/components/src/ListingHistoryEvent/types.ts, packages/components/src/PhaseCountdown/__snapshots__/PhaseCountdown.stories.storyshot, packages/components/src/StepProcess/__snapshots__/StepProcess.stories.storyshot, packages/components/src/__snapshots__/LoadingIndicator.stories.storyshot, packages/components/src/__snapshots__/Message.stories.storyshot, packages/components/src/__snapshots__/Modal.stories.storyshot, packages/components/src/__snapshots__/ModalContent.stories.storyshot, packages/components/src/__snapshots__/QuestionToolTip.stories.storyshot, packages/components/src/__snapshots__/SubmitChallengeModal.stories.storyshot, packages/components/src/index.ts, packages/dapp/src/components/listing/ListingEvent.tsx, packages/dapp/src/components/listing/ListingHistory.tsx, packages/dapp/src/components/utility/HigherOrderComponents.tsx, packages/dapp/src/reducers/listings.ts
This update handles Listing History events excluding Appeal Phases
=> Apply designs to Listing History on the Listing Details page

packages/contracts/contracts/tcr/AddressRegistry.sol
- explicitly check if a listing is whitelisted when trying to challenge, to match standard implementation
=> Respond to Audit Finding 3.38

packages/core/src/civil.ts, packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/contracts/tcr/council.ts, packages/core/src/contracts/tcr/government.ts, packages/core/src/contracts/utils/contracts.ts, packages/dapp/src/actionCreators/government.ts, packages/dapp/src/apis/civilTCR.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/council/Government.tsx, packages/dapp/src/components/council/SetAppellate.tsx, packages/dapp/src/components/listing/AppealDetail.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/helpers/government.ts, packages/dapp/src/reducers/government.ts, packages/dapp/src/reducers/index.ts
- Create Council class that wraps TCR & Government contracts and can grant appeals
- Show 'grant appeal button' only if current user is member of council
=> Council Multisig Support

packages/dapp/package.json
=> increase old space

packages/core/src/contracts/newsroom.ts
Its slightly cheaper to publish as an editor than to go through the multisig, so we should preference publishing that way whenever possible
=> preference publishing as an editor over owner [ch1906]

packages/contracts/contracts/tcr/AddressRegistry.sol
- fixing check on challenging listing with resolved challenge
=> Respond to Audit Finding 3.37

packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/test/tcr/registryWithAppeals/claimAppealChallengeReward.ts
- fixing but in claimAppealChallengeReward
- adding unit tests to cover
=> Responding to Audit Issue 55

packages/contracts/contracts/installed_contracts/PLCRVoting.sol, packages/contracts/contracts/tcr/AddressRegistry.sol, packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/contracts/tcr/ContractAddressRegistry.sol, packages/contracts/contracts/tcr/RestrictedAddressRegistry.sol, packages/contracts/migrations/8_registry.ts, packages/contracts/test/tcr/registry/appWasMade.ts, packages/contracts/test/tcr/registry/exit.ts, packages/contracts/test/tcr/registry/hasClaimedTokens.ts, packages/contracts/test/tcr/registry/tokenClaims.ts, packages/contracts/test/tcr/registry/updateStatus.ts, packages/contracts/test/tcr/registryWithAppeals/hasClaimedChallengeAppealTokens.ts, packages/contracts/test/utils/contractutils.ts
- Copying latest standard implementation of Registry into AddressRegistry, updating it to use addresses instead of bytes32, updating visibility of some functions so they can be overwritten
- Fixing tests after changes
=> Respond to Audit Finding 3.13

packages/components/src/ClaimRewards.tsx, packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/contracts/tcr/voting.ts, packages/core/src/types.ts, packages/dapp/src/apis/civilTCR.ts, packages/dapp/src/components/listing/ChallengeRewardsDetail.tsx, yarn.lock
- adding event data to UserChallengeData so we have salt and numtokens ready to use in DApp
- removing salt input from claim rewards since we already have it
=> core updates

packages/contracts/conf/config.json, packages/contracts/contracts/tcr/Government.sol, packages/contracts/migrations/6_government.ts, packages/contracts/test/tcr/government/get.ts, packages/contracts/test/tcr/government/processProposal.ts, packages/contracts/test/tcr/government/proposeReparameterization.ts, packages/contracts/test/tcr/government/set.ts, packages/contracts/test/utils/contractutils.ts
- Adding voting process for changing government parameters
=> Responding to Audit Issue 56

packages/components/src/PhaseCountdown/__snapshots__/PhaseCountdown.stories.storyshot, packages/components/src/ReviewVote/__snapshots__/ReviewVote.stories.storyshot, packages/components/src/WalletOnboarding.tsx, packages/components/src/__snapshots__/Modal.stories.storyshot, packages/components/src/__snapshots__/ModalContent.stories.storyshot, packages/components/src/__snapshots__/QuestionToolTip.stories.storyshot, packages/components/src/__snapshots__/SubmitChallengeModal.stories.storyshot, packages/components/src/index.ts, packages/newsroom-manager/package.json, packages/newsroom-manager/src/Newsroom.tsx
Basically no changes, just copy-paste and moving some props around.
=> Move wallet onboarding into this repo

.prettierignore, packages/contracts/contracts/newsroom/Newsroom.sol, packages/contracts/test/newsroom/newsroom.ts
Added replay attack safety for Newsroom smart-contract
=> Respond to Audit Finding 3.1 and 3.4

packages/components/src/ListingDetailPhaseCard/__snapshots__/ListingDetailsPhaseCard.stories.storyshot, packages/components/src/ListingHistoryEvent/__snapshots__/ListingHistoryEvent.stories.storyshot, packages/components/src/ListingSummary/__snapshots__/ListingSummary.stories.storyshot, packages/components/src/NavBar/__snapshots__/NavBar.stories.storyshot, packages/components/src/PhaseCountdown/SmallProgressBarCountdownTimer.tsx, packages/components/src/PhaseCountdown/__snapshots__/PhaseCountdown.stories.storyshot, packages/components/src/PhaseCountdown/constants.ts, packages/components/src/PhaseCountdown/styledComponents.tsx, packages/components/src/PhaseCountdown/textComponents.tsx, packages/components/src/PhaseCountdown/types.ts, packages/components/src/ReviewVote/ReviewVoteModal.tsx, packages/components/src/ReviewVote/__snapshots__/ReviewVote.stories.storyshot, packages/components/src/StepProcess/__snapshots__/StepProcess.stories.storyshot, packages/components/src/Tabs/__snapshots__/Tabs.stories.storyshot, packages/components/src/__snapshots__/LoadingIndicator.stories.storyshot, packages/components/src/__snapshots__/Message.stories.storyshot, packages/components/src/__snapshots__/Modal.stories.storyshot, packages/components/src/__snapshots__/ModalContent.stories.storyshot, packages/components/src/__snapshots__/QuestionToolTip.stories.storyshot, packages/components/src/__snapshots__/SubmitChallengeModal.stories.storyshot, packages/components/src/__snapshots__/ViewTransactionLink.stories.storyshot, packages/components/src/input/__snapshots__/AddressInput.stories.storyshot, packages/components/src/input/__snapshots__/Dropdown.stories.storyshot, packages/components/src/input/__snapshots__/Input.stories.storyshot, packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/utility/HigherOrderComponents.tsx, packages/dapp/src/selectors/index.ts
- Fix vote text in Review Vote modal
- Fix My Activity items to show the correct state for challenges thatare in Commit or Reveal phases
- Update styles for Activity Item phase countdown
- Refactor Activity Item phase countdown to use textComponents for UI strings
=> DApp UI bug fixes for My Activity and Review Vote modal

packages/components/src/TCRUserDashboard/DashboardActivity.tsx, packages/components/src/TCRUserDashboard/DashboardActivityItem.tsx, packages/components/src/TCRUserDashboard/DashboardUserInfoSummary.tsx, packages/components/src/Tabs/__snapshots__/Tabs.stories.storyshot, packages/dapp/src/components/Dashboard/ActivityList.tsx, packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/selectors/index.ts
- Re-organize the tabs in My Activity
- Add filter tabs for 'Voting' challenges (ie: Reveal, Claim Rewards, Rescue Tokens)
- Fix bug preventing correct 'Reveal Vote' message from displaying in My Activity
=> Updates for My Activity view in DApp

packages/contracts/conf/config.json, packages/contracts/contracts/tcr/Government.sol, packages/contracts/migrations/6_government.ts, packages/contracts/test/tcr/government/processConstChangeProp.ts, packages/contracts/test/tcr/government/proposeNewConstitution.ts, packages/contracts/test/tcr/government/proposeReparameterization.ts, packages/contracts/test/utils/contractutils.ts
- adding functionality for appellate to propose new constitution values
- unit tests
=> Constitution Voting

packages/components/src/ApplicationPhaseStatusLabels.tsx, packages/components/src/ListingSummary/ListingSummary.tsx, packages/components/src/NavBar/__snapshots__/NavBar.stories.storyshot, packages/components/src/PhaseCountdown/__snapshots__/PhaseCountdown.stories.storyshot, packages/components/src/ReviewVote/__snapshots__/ReviewVote.stories.storyshot, packages/components/src/TCRUserDashboard/DashboardActivity.tsx, packages/components/src/TCRUserDashboard/DashboardActivityTabTitle.tsx, packages/components/src/TCRUserDashboard/index.ts, packages/components/src/TCRUserDashboard/styledComponents.tsx, packages/components/src/TCRUserDashboard/textComponents.tsx, packages/components/src/__snapshots__/Modal.stories.storyshot, packages/components/src/__snapshots__/ModalContent.stories.storyshot, packages/components/src/__snapshots__/QuestionToolTip.stories.storyshot, packages/components/src/__snapshots__/SubmitChallengeModal.stories.storyshot, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/selectors/index.ts
- Fix rendering of Challenges Awaiting Appeal Requests on the main registry page
- Refactor tab titles for My Activity/Dashboard view
=> UI updates for the main registry page and My Activity

packages/components/src/PhaseCountdown/constants.ts, packages/components/src/PhaseCountdown/textComponents.tsx, packages/components/src/TCRUserDashboard/styledComponents.tsx, packages/dapp/src/components/Dashboard/ActivityList.tsx, packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/utility/HigherOrderComponents.tsx
- Fix partial results graphs in activity item view to show correct
counts and pct
- Fix duping of resolved challenge activity items
- Add correct labeling for Challenges Awaiting Appeal Request to
activity view
=> DApp UI updates and fixes

packages/contracts/test/tcr/registryWithAppeals/challengeCanBeResolved.ts
- adding unit tests for challengeCanBeResolved
=> Responding to Audit Finding 3.23

packages/components/src/NavBar/__snapshots__/NavBar.stories.storyshot, packages/components/src/PhaseCountdown/__snapshots__/PhaseCountdown.stories.storyshot, packages/components/src/ReviewVote/__snapshots__/ReviewVote.stories.storyshot, packages/components/src/TCRUserDashboard/DashboardUserInfoSummary.tsx, packages/components/src/TCRUserDashboard/index.ts, packages/components/src/TCRUserDashboard/styledComponents.tsx, packages/components/src/TCRUserDashboard/textComponents.tsx, packages/components/src/Tabs/__snapshots__/Tabs.stories.storyshot, packages/components/src/__snapshots__/Modal.stories.storyshot, packages/components/src/__snapshots__/ModalContent.stories.storyshot, packages/components/src/__snapshots__/QuestionToolTip.stories.storyshot, packages/components/src/__snapshots__/SubmitChallengeModal.stories.storyshot, packages/core/src/contracts/tcr/voting.ts, packages/core/src/utils/listingDataHelpers/pollHelper.ts, packages/dapp/src/apis/civilTCR.ts, packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/Dashboard/ReclaimTokens.tsx, packages/dapp/src/components/Dashboard/UserInfoSummary.tsx, packages/dapp/src/selectors/index.ts
- Style tweaks
- Refactor a bunch of components and text into `styleComponents` and `textComponents` files
- Update `pollHelper` to return correct value for `didChallengeSucceed`
- Add selectors / rendering code for total CVL won in Challenges started by user
- Add selectors / rendering code for approx amount of unclaimed rewards for a successful challenge the user supported
- Add multi-rescue tokens functionality
- Add basic Withdraw Voting Rights form
=> DApp: UI updates for My Activity

packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/Dashboard/ReclaimTokens.tsx, packages/dapp/src/selectors/index.ts
- Fix multi-rescue tokens call so it passes the correct challenge IDs
- Check if a user rescued tokens in the challenges w/ rescue tokens
selector
- Use the proper multiplier when withdrawing tokens from the voting
contract
=> Fixes for Dashboard/My Activity view

packages/contracts/contracts/tcr/CivilTCR.sol
- use safemath everywhere in CivilTCR.sol
=> Respond to Audit Finding 3.7

packages/contracts/test/tcr/registryWithAppeals/appealChallengeCanBeResolved.ts
- adding unit tests for appealChallengeCanBeResolved
=> Respond to Audit Finding 3.24

packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/migrations/9_registry.ts, packages/contracts/test/tcr/parameterizer/canBeSet.ts, packages/contracts/test/tcr/parameterizer/challengeCanBeResolved.ts, packages/contracts/test/tcr/parameterizer/challengeReparameterization.ts, packages/contracts/test/tcr/parameterizer/claimReward.ts, packages/contracts/test/tcr/parameterizer/get.ts, packages/contracts/test/tcr/parameterizer/processProposal.ts, packages/contracts/test/tcr/parameterizer/propExists.ts, packages/contracts/test/tcr/parameterizer/proposeReparameterization.ts, packages/contracts/test/tcr/parameterizer/voterReward.ts, packages/contracts/test/tcr/plcrVoting/commitVote.ts, packages/contracts/test/tcr/plcrVoting/didCommit.ts, packages/contracts/test/tcr/plcrVoting/didReveal.ts, packages/contracts/test/tcr/plcrVoting/revealVote.ts, packages/contracts/test/utils/contractutils.ts
- call token telemetry's onTokensUsed when applying and appealing
=> Prove Use Part 2

packages/components/src/ListingDetailPhaseCard/AppealChallengeRevealVoteCard.tsx, packages/components/src/ListingDetailPhaseCard/ChallengeRevealVoteCard.tsx, packages/components/src/ListingDetailPhaseCard/ListingDetailsPhaseCard.stories.tsx, packages/components/src/ListingDetailPhaseCard/RevealVote.tsx, packages/components/src/ListingDetailPhaseCard/types.ts, packages/components/src/Parameterizer/ChallengeProposalRevealVote.tsx, packages/dapp/src/components/Parameterizer/ChallengeProposalDetail.tsx, packages/dapp/src/components/listing/AppealChallengeDetail.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/helpers/vote.ts
- store vote option locally when committing vote
- fetch and select proper option when revealing
=> save and load vote option

packages/contracts/test/tcr/registryWithAppeals/claimAppealChallengeReward.ts
- more unit tests around appeal challenge rewards
=> Respond to Audit Finding 3.25

packages/contracts/contracts/tcr/CivilTCR.sol
- throw in appealChallengeCanBeResolved if no challenge exists
=> Respond to Audit Finding 3.27

packages/contracts/test/tcr/registryWithAppeals/appealCanBeResolved.ts
- more unit tests for appealCanBeResolved
=> Respond to Audit Finding 3.26

packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/contracts/tcr/council.ts
fixing bug on granting appeal and one where application events weren't being included
=> 2 bug fixes

packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/contracts/tcr/Government.sol, packages/contracts/migrations/7_government.ts, packages/contracts/test/tcr/registryWithAppeals/claimAppealChallengeReward.ts, packages/contracts/test/utils/contractutils.ts, packages/core/src/contracts/tcr/council.ts
- same as https://github.com/joincivil/Civil/pull/448 but that one seems messed up
=> secondary audit feedback 2

packages/contracts/conf/config.json, packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/contracts/tcr/Government.sol, packages/contracts/migrations/10_government.ts, packages/contracts/test/utils/contractutils.ts
- using a separate government parameter for appeal challenge vote distribution percentage
=> Respond to Extended Audit Issue 69

packages/contracts/contracts/tcr/CivilTCR.sol, packages/contracts/test/tcr/registryWithAppeals/allUserRewards.ts, packages/contracts/test/utils/contractutils.ts
- adding unit tests verifying rewards for all participants in a challenge process
- fixing bug found while writing tests
=> more unit tests

packages/dapp/src/components/listing/ListingCharter.tsx, packages/dapp/src/components/listing/ListingHeader.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx
putting charter JSON parsing inside try catch block so it doesn't break the page
=> Quick Charter Rendering Fix

packages/dapp/src/components/GlobalNav.tsx, packages/dapp/src/components/listing/ListingRedux.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/WhitelistedListingItem.tsx, packages/dapp/src/helpers/listingEvents.ts, packages/dapp/src/redux/actionCreators/listings.ts, packages/dapp/src/redux/actionCreators/ui.ts, packages/dapp/src/redux/reducers/index.ts, packages/dapp/src/redux/reducers/listings.ts, packages/dapp/src/redux/reducers/newsrooms.ts, packages/dapp/src/redux/reducers/ui.ts
=> redux refactor

packages/components/src/NavBar/NavBar.tsx
=> Disable the nav "drawer" if there is no logged in user

packages/dapp/src/components/Main.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/WhitelistedListingItem.tsx, packages/dapp/src/components/utility/HigherOrderComponents.tsx, packages/dapp/src/helpers/queryTransformations.ts, packages/dapp/src/redux/actionCreators/ui.ts
- modify higher order component connector to be able to use data from redux or graphql
- small fixes for displaying challenge statement on listing list items
=> Graphql Challenge

packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/listing/AppealChallengeCommitVote.tsx, packages/dapp/src/components/listing/AppealChallengeDetail.tsx, packages/dapp/src/components/listing/AppealDetail.tsx, packages/dapp/src/components/listing/Challenge.tsx, packages/dapp/src/components/listing/ChallengeCommitVote.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/ListingRedux.tsx, packages/dapp/src/selectors/index.ts
- eliminate need to pass in newsroom to challenge detail component, was causing issues and only used for name which isn't that important
=> Fixing Challenge Detail Component

packages/ethapi/src/ethapi.ts
This fixes all the annoying errors with callbacks not firing after transactions
=> wait for the block to be confirmed before going further

packages/dapp/src/components/listinglist/WhitelistedListingListContainer.tsx, packages/dapp/src/components/listinglist/WhitelistedListingListRedux.tsx
=> Group and render whitelisted + currently challenged newsroom listings together

packages/components/src/NavBar/NavBar.tsx, packages/components/src/NavBar/NavMenu.tsx
Only show Log In button if user is not signed in (hide CVL token svg and other user specific UI elements)
=> UI fixes for the DApp Top Nav

packages/dapp/src/components/utility/HigherOrderComponents.tsx
This PR addressed the issue where some listing detail pages were not loading properly when GraphQL was enabled.
=> Use GraphQL in `connectChallengePhase` HOC, if applicable

packages/core/src/types.ts, packages/dapp/src/components/listinglist/ListingList.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/utility/HigherOrderComponents.tsx, packages/dapp/src/helpers/queryTransformations.ts, packages/dapp/src/helpers/transforms.ts
- add prevChallenge to graphql query
- modifying ListingListItem to avoid HOC if prevChallenge already there
=> On Rejected Listings Page Load Rejections via GraphQL

packages/components/src/ListingSummary/ListingSummary.stories.tsx, packages/components/src/ListingSummary/NewsroomInfo.tsx, packages/components/src/ListingSummary/types.ts, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/WhitelistedListingItem.tsx
@am9u I know you're working on charter in listing stuff, hope this doesn't conflict with anything, had this on my machine from before the break, cleans listing summaries a bit.
Fixes #714
=> Fix missing charter logo on rejected listings, DRY code

packages/dapp/src/components/Dashboard/ActivityListItem.tsx
- so they show up properly when loading via graphql
- kind of a hack until we get better dashboard support via graphql
=> load listing data for dashboard activity items

packages/core/src/contracts/tcr/appeal.ts, packages/dapp/src/components/listing/ListingChallengeStatement.tsx, packages/dapp/src/components/listing/ListingRedux.tsx
- getting challenge statements to load properly via graphql and web3
=> Fix Challenge Statement Rendering

packages/dapp/src/components/listing/ListingOwnerActions.tsx, packages/dapp/src/selectors/index.ts
- wrapping some pieces of selectors in try catches because otherwise they break things when switching accounts
=> Fix Account Switching Bug

packages/dapp/src/components/listing/AppealChallengeCommitVote.tsx, packages/dapp/src/components/listing/AppealChallengeRevealVote.tsx, packages/dapp/src/components/listing/ListingEvent.tsx, packages/dapp/src/components/listing/ListingHistory.tsx, packages/dapp/src/components/listing/SubmitAppealChallenge.tsx
fixes for challenging granted appeal, voting on granted appeal challenge, event timestamps
=> a few tiny fixes

packages/dapp/src/components/listing/ListingHistory.tsx
https://github.com/joincivil/Civil/issues/654
=> reverse graphql listing history

packages/components/src/ChallengeResultsChart/ChallengeResults.tsx, packages/components/src/ListingDetailPhaseCard/AppealChallengeResolveCard.tsx, packages/components/src/ListingDetailPhaseCard/AppealDecisionDetail.tsx, packages/components/src/ListingSummary/ChallengeOrAppealStatementSummary.tsx, packages/components/src/ListingSummary/ListingSummaryUnderChallenge.tsx, packages/components/src/ListingSummary/types.ts, packages/core/src/utils/listingDataHelpers/pollHelper.ts, packages/dapp/src/components/listing/AppealAwaitingDecision.tsx, packages/dapp/src/components/listing/AppealChallengeCommitVote.tsx, packages/dapp/src/components/listing/AppealChallengeResolve.tsx, packages/dapp/src/components/listing/AppealChallengeRevealVote.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/RejectedListingListContainer.tsx, packages/dapp/src/components/listinglist/RejectedListingListRedux.tsx, packages/dapp/src/helpers/transforms.ts
Addresses: #756, #791, #794, #801
=> Various bug fixes for the listings on the Registry page in Appeal and Appeal Challenge states

packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/contracts/tcr/voting.ts, packages/dapp/src/components/listing/ListingHistory.tsx, packages/dapp/src/helpers/listingEvents.ts
- update user activity when they reveal/collect/rescue during a session 
https://github.com/joincivil/Civil/issues/781
=> User Activity Updates

packages/components/src/NavBar/NavMenu.tsx, packages/components/src/NavBar/__snapshots__/NavBar.stories.storyshot, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/listinglist/EmptyRegistryTabContent.tsx, packages/dapp/src/components/listinglist/Listings.tsx
fixes https://github.com/joincivil/Civil/issues/837
=> change createNewsroom URL to create-newsroom to match standard

packages/core/src/contracts/tcr/civilTCR.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/listing/ListingChallengeStatement.tsx, packages/dapp/src/components/listing/SubmitAppealChallenge.tsx, packages/dapp/src/helpers/listingEvents.ts
- items appearing in Claim Rewards should be correct now
=> Claim Rewards Fixes

packages/core/src/utils/listingDataHelpers/listingHelper.ts
=> If a listing is whitelisted already, it can't be In Application

packages/components/src/Button.tsx, packages/components/src/ListingDetailHeader/ListingDetailHeader.tsx, packages/components/src/ListingDetailHeader/ListingDetailHeaderStyledComponents.tsx, packages/components/src/__snapshots__/Button.stories.storyshot, packages/components/src/icons/NorthEastArrow.tsx
=> Render the newsroom's URL in the Listing Detail page header

packages/components/src/TCRUserDashboard/Dashboard.tsx, packages/components/src/TCRUserDashboard/DashboardUserInfoSummary.tsx, packages/components/src/TCRUserDashboard/styledComponents.tsx, packages/components/src/styleConstants.ts
This update includes some minor styling updates for the Dapp Dashboard.
More expansive UI updates will be part of on upcoming PR.
=> Styling updates for Dashboard

packages/components/src/ChallengeResultsChart/VoteTypeSummaryRow.tsx, packages/core/src/contracts/tcr/listing.ts, packages/dapp/src/components/Dashboard/ActivityListAppealChallengeItem.tsx, packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/Dashboard/ChallengesWithRewardsToClaim.tsx, packages/dapp/src/components/Dashboard/ChallengesWithTokensToRescue.tsx, packages/dapp/src/helpers/listingEvents.ts
- fix checkboxes in My Activity
- null ref fix
- add appeal challenge event to redux history
=> Small Random Fixes

packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/types.ts, packages/core/src/utils/listingDataHelpers/challengeHelper.ts, packages/dapp/src/selectors/index.ts
get unclaimed reward amount directly from contract instead of doing complicated things
=> Fix Unclaimed Reward Amount

packages/components/src/TCRUserDashboard/DashboardActivityItemTask.tsx, packages/components/src/TCRUserDashboard/DashboardActivityItemTitle.tsx, packages/components/src/TCRUserDashboard/DashboardActivitySelectableItem.tsx, packages/components/src/TCRUserDashboard/DashboardTypes.ts, packages/dapp/src/components/Dashboard/ActivityListItemClaimReward.tsx, packages/dapp/src/components/Dashboard/ActivityListItemRescueTokens.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/Dashboard/MyTasksItem.tsx, packages/dapp/src/components/Main.tsx
This updates includes:
- Linking activity item titles to listing or challenge detail pages
- Refactoring of tab/subtabs so they are all deep-linkable
- Adding placeholder transfer to PLCR message
Issues: #890 #893
=> Various minor UI updates for Dashboard

packages/components/src/AuthenticatedRoute.tsx, packages/components/src/TokenTutorial/TokenTutorial.stories.tsx, packages/components/src/TokenTutorial/TokenTutorial.tsx, packages/components/src/TokenTutorial/TokenTutorialLanding.tsx, packages/components/src/TokenTutorial/TokenTutorialQuiz.tsx, packages/components/src/TokenTutorial/TokenTutorialTextComponents.tsx, packages/components/src/TokenTutorial/TutorialWelcomeScreens.tsx, packages/components/src/Tokens/Tokens.tsx, packages/dapp/src/components/Account/LoadUser.tsx, packages/dapp/src/components/Account/UserInfo.tsx, packages/dapp/src/components/Tokens/Tokens.tsx, packages/utils/src/apolloClient.ts
* Connects quiz to back end (CIVIL-249)
* Saves and reads 
* Fixes a dumb redirect bug.
=> Connects Quiz to Backend

packages/dapp/src/components/listing/ListingHeader.tsx
fixes https://github.com/joincivil/Civil/issues/906
=> fix label for newsrooms in application stage

.circleci/config.yml
- Push `master` to staging only
- New branch `production` deploys to production
- Pushes any `test/*` branches to new test environment.
CIVIL-341
=> Updates to CircleCI Configs w/ New Branch Deploys

packages/dapp/src/components/Parameterizer/ChallengeProposalCommitVote.tsx
- Pass salt properly as part of the transaction and make sure salt is
displaying in the Review Vote view
#916
=> Fixes for Commit Vote to Parameterizer Challenge

packages/dapp/src/helpers/listingEvents.ts
- adding retry logic to getIPFSContent since this fails mysteriously a fair amount, but subsequent attempts are likely successful
=> Adding Retry Logic to getIPFSContent

packages/dapp/src/components/listing/ListingEvent.tsx
fixes https://github.com/joincivil/Civil/issues/923
=> support the 'Overturned' challenge events

packages/dapp/src/components/Main.tsx, packages/utils/src/apolloClient.ts
- change default network for apollo client and set network on load
=> couple more network fixes

packages/dapp/src/components/Main.tsx, packages/dapp/src/redux/reducers/ui.ts
- always load via graphql at first, prevent rendering of listings if on wrong network
=> network updates

packages/dapp/src/selectors/index.ts
- make sure when getting claimedRewards we're including appeal challenge rewards
=> fix rewards claimed

packages/components/src/Parameterizer/ChallengeProposalCommitVote.tsx, packages/components/src/Parameterizer/ChallengeProposalRevealVote.tsx, packages/dapp/src/components/Parameterizer/ChallengeProposalDetail.tsx
- render proposal voting cards differently based on if user has already committed/revealed
=> Param Proposal Vote Cards

packages/core/package.json, packages/core/src/content/ipfsprovider.ts, packages/core/src/globals.d.ts, yarn.lock
- should have no effect
- ignore first commit, part of another PR
=> update ipfs package

packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/dapp/src/components/Dashboard/ChallengesWithRewardsToClaim.tsx, packages/dapp/src/components/Dashboard/ChallengesWithTokensToRescue.tsx, packages/dapp/src/components/Dashboard/MyTasks.tsx, packages/dapp/src/components/Main.tsx
This PR also includes a fix routing for the Dashboard Newsrooms view
=> Add sorting for Dashboard activity items

packages/components/src/EmailSignup/EmailSignup.tsx, packages/components/src/EmailSignup/EmailSignupSuccess.tsx, packages/components/src/EmailSignup/__snapshots__/EmailSignup.stories.storyshot
Updates the link to the @civil_alerts account on the signup.
=> Updates Registry Alerts Twitter Account Name

packages/artifacts/v1/Government.json, packages/contracts/conf/config.json, packages/contracts/migrations/20_government_take2.ts
changed judgeAppealPhaseLength to 1209600
=> deploy new government contract

packages/dapp/src/components/Main.tsx, packages/newsroom-signup/src/AuthWrapper.tsx
For https://github.com/joincivil/civil-api-server/pull/125, alongside #1017
=> Update newsroom signup to handle token in query string [CIVIL-435]

packages/newsroom-signup/src/NewsroomProfile/GrantApplication.tsx, packages/newsroom-signup/src/NewsroomProfile/index.tsx
We say "you can go back and edit at any time" and design has button https://consensys.invisionapp.com/d/#/console/16220120/343734570/preview
=> Back button should be visible when grant not requested

packages/core/src/types.ts, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/listing/ListingPhaseActions.tsx, packages/dapp/src/components/listing/WhitelistedDetail.tsx, packages/dapp/src/components/listinglist/ListingListItem.tsx, packages/dapp/src/components/listinglist/WhitelistedListingItem.tsx, packages/dapp/src/helpers/queryTransformations.ts
- get approval date from graphql instead of by subscribing to events when graphql enabled
=> fix approval date not showing up on some browsers

packages/dapp/src/components/listinglist/RejectedListingListContainer.tsx, packages/dapp/src/components/listinglist/WhitelistedListingListContainer.tsx
- use cursor pagination for whitelisted/rejected listing queries
=> Pagination for Queries

packages/components/src/UserStatement/RequestAppealStatement.tsx, packages/components/src/UserStatement/SubmitAppealChallengeStatement.tsx, packages/components/src/UserStatement/SubmitChallengeStatement.tsx
fixes https://github.com/joincivil/Civil/issues/882
=> statement copy fixes

packages/dapp/src/components/listing/RequestAppeal.tsx, packages/dapp/src/components/listing/SubmitAppealChallenge.tsx, packages/dapp/src/components/listing/SubmitChallenge.tsx
- fix listing URL for cancel button on submitting challenge/appeal/appealChallenge
=> fix cancel button on 3 modals

packages/dapp/src/components/Dashboard/DashboardActivity.tsx
- instead of loading via web3 which is broken-ish
=> get user dashboard newsroom address from graphql query

packages/dapp/src/components/utility/TransactionStatusModalsHOC.tsx
=> Fix styling for Post to IPFS modals for the DApp

.circleci/config.yml
small change when deploying test env
=> escape newlines

packages/components/src/ListingDetailPhaseCard/InApplicationResolveCard.tsx, packages/components/src/ListingDetailPhaseCard/WhitelistedCard.tsx, packages/dapp/src/components/listing/AppealAwaitingDecision.tsx, packages/dapp/src/components/listing/AppealChallengeCommitVote.tsx, packages/dapp/src/components/listing/AppealChallengeResolve.tsx, packages/dapp/src/components/listing/AppealChallengeRevealVote.tsx, packages/dapp/src/components/listing/AppealResolve.tsx, packages/dapp/src/components/listing/AppealSubmitChallenge.tsx, packages/dapp/src/components/listing/ApplicationUpdateStatus.tsx, packages/dapp/src/components/listing/ChallengeCommitVote.tsx, packages/dapp/src/components/listing/ChallengeDetail.tsx, packages/dapp/src/components/listing/ChallengeResolve.tsx, packages/dapp/src/components/listing/ChallengeRevealVote.tsx, packages/dapp/src/components/listing/ListingPhaseActions.tsx, packages/dapp/src/components/listing/WhitelistedDetail.tsx, packages/utils/src/urlConstants.ts
=> Fix FAQ url in the Challenge Commit Vote card on the Listing Detail page

.circleci/config.yml, packages/dapp/src/helpers/config.ts, packages/dapp/src/index.tsx
https://docs.sentry.io/workflow/releases/?platform=browser
=> add release tag to sentry config

packages/dapp/src/components/Dashboard/Dashboard.tsx
just saw this pop up in Sentry
=> fix ethereum typo

packages/components/src/ListingDetailPhaseCard/textComponents.tsx
=> Update copy for Reveal Vote action to indicate salt is stored in localstorage

packages/newsroom-signup/src/SmartContract/AddMember.tsx, packages/newsroom-signup/src/SmartContract/AddMembersToContract.tsx, packages/newsroom-signup/src/SmartContract/index.tsx
@picocassette should review this once its merged before deploy
=> CIVIL-543 add remove role ability to newsroom onboarding

packages/newsroom-signup/src/NewsroomProfile/CharterQuestions.tsx, packages/utils/src/urlConstants.ts
still needs link for sample charter. @picocassette
=> CIVIL-620 charter support copy

packages/dapp/src/components/Dashboard/DashboardPage.tsx, packages/dapp/src/components/Main.tsx, packages/dapp/src/components/Tokens/StorefrontPage.tsx
=> code split main routes

packages/components/src/features/index.ts, packages/components/src/index.ts, packages/dapp/config-overrides.js, packages/dapp/package.json, packages/dapp/src/components/Dashboard/ActivityList.tsx, packages/dapp/src/components/Dashboard/ActivityListItem.tsx, packages/newsroom-manager/src/RosterMember.tsx, yarn.lock
Note that build will fail until we merge updates to civil-sdk master and release is auto-published to npm.
=> Embed boost creation form in dapp [CIVIL-735]

packages/dapp/devops/nginx.conf, packages/dapp/devops/start.sh
going to try this out in the test enviroment before putting on staging
=> prerender.io

packages/components/src/styleConstants.ts, packages/dapp/package.json, packages/dapp/src/components/Boosts/Boost.tsx, packages/dapp/src/components/Boosts/BoostCreate.tsx, packages/dapp/src/components/Main.tsx, packages/dapp/src/constants.ts, yarn.lock
Build will fail until https://github.com/joincivil/civil-sdk/pull/25 merged and version bumped here.
=> Edit Boost page [CIVIL-736]

packages/dapp/package.json, packages/dapp/src/components/Boosts/BoostCreate.tsx, packages/dapp/src/components/listing/ListingBoosts.tsx, packages/dapp/src/components/listing/ListingDiscourse.tsx, packages/dapp/src/components/listing/ListingRedux.tsx, packages/dapp/src/components/listing/styledComponents.tsx, packages/dapp/src/components/listinglist/TabDescriptions.tsx, yarn.lock
- add boosts to listing page
- fix navigation issue in create boosts
- hotfix for discourse widget
=> 7/15/19 Release

packages/components/src/WithNewsroomChannelHOC.tsx
So that we can use this HOC on `BoostForm` in civil-sdk which uses `newsroomContractAddress` prop name.
=> Newsroom channel HOC support `newsroomContractAddress` prop name too

packages/dapp/src/components/Boosts/BoostCreate.tsx
fix: wrap BoostForm in a Query that gets channel id from newsroom add…ress. fixes launch-boost page when accessed via top-nav
=> HOTFIX 8/21/19 - Fix Launch Boost via Top Nav

packages/dapp/src/components/Boosts/BoostCreate.tsx
fix: wrap BoostForm in a Query that gets channel id from newsroom address. fixes launch-boost page when accessed via top-nav
=> Bring Create Boost Hotfix into Master

packages/components/package.json, packages/contracts/package.json, packages/core/package.json, packages/dapp/package.json, packages/dev-utils/package.json, packages/ethapi/package.json, packages/ethapi/src/helpers.ts, packages/newsroom-manager/package.json, packages/newsroom-signup/package.json, packages/typescript-types/package.json, packages/utils/package.json, yarn.lock
this will be needed before we upgrade react-apollo
=> build(utils): upgrade typescript

packages/components/src/Account/Auth/AuthStyledComponents.tsx, packages/components/src/Account/Auth/UserSetEmail.tsx, packages/components/src/Account/Auth/UserSetHandle.tsx, packages/components/src/Account/Auth/__snapshots__/EmailAuth.stories.storyshot, packages/components/src/Account/Auth/__snapshots__/UserSetEmail.stories.storyshot, packages/utils/src/handle.ts
- update handle validation and check for uniqueness when user stops typing
- update set email component copy
=> feat: handle validation

packages/components/src/TCRUserDashboard/DashboardTextComponents.tsx, packages/components/src/Tokens/TokensAccountSignup.tsx, packages/components/src/Tokens/TokensTextComponents.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/newsroom-signup/src/AuthWrapper.tsx
- better messaging when no tasks/challenges
=> fix: update login to remove old flow in some places

packages/components/src/Tutorial/__snapshots__/Tutorial.stories.storyshot, packages/components/src/input/__snapshots__/Input.stories.storyshot, packages/dapp/src/components/Main.tsx, packages/elements/src/inputs/RadioInput.tsx, packages/ethapi/src/ethapi.ts, packages/kirby/package.json, packages/kirby/src/KirbyApp.tsx, packages/kirby/src/plugins/CivilID.ts, packages/kirby/src/views/identity/Login.tsx, packages/kirby/src/views/identity/Signup.tsx, yarn.lock
also logs the user out if they change their metamask account
=> fix(dapp): clean up login/signup style

packages/kirby/package.json, packages/kirby/src/views/Web3Enable.tsx, yarn.lock
if logged out of portis from another window and then reload the page the portis login screen will be displayed from the iframe, but the kirby view is not displayed so the user cannot do anything.
=> fix(kirby): show web3enable view on saved preference

packages/components/src/Contributors/ContributorCount.tsx, packages/components/src/Contributors/Contributors.stories.tsx, packages/components/src/Contributors/Contributors.tsx, packages/components/src/Contributors/ContributorsStyledComponents.tsx, packages/components/src/Contributors/__snapshots__/Contributors.stories.storyshot, packages/components/src/Contributors/types.ts, packages/components/src/StoryFeed/StoryFeed.stories.tsx, packages/components/src/StoryFeed/__snapshots__/StoryFeed.stories.storyshot, packages/components/src/input/__snapshots__/Input.stories.storyshot, packages/dapp/src/components/StoryFeed/StoryFeed.tsx, packages/elements/src/inputs/Input.tsx
- fix for default network kirby issue
- boost contribution amount input fix
=> Prod Release Oct 15 2019 12:30pm

packages/sdk/src/react/boosts/BoostFeed.tsx
- fix for ETH wallet on prod issue
=> Prod Release Oct 18 2019

packages/components/src/Account/Auth/UserSetAvatar.tsx, packages/components/src/Account/Auth/UserSetEmail.tsx, packages/components/src/Account/Auth/__snapshots__/UserSetAvatar.stories.storyshot, packages/components/src/Account/Auth/__snapshots__/UserSetEmail.stories.storyshot, packages/components/src/TCRUserDashboard/DashboardStyledComponents.tsx, packages/components/src/input/ImageFileToDataUri.tsx, packages/core/src/contracts/multisig/basemultisigproxy.ts, packages/core/src/contracts/multisig/multisig.ts, packages/dapp/src/components/listing/ListingCharterRosterMember.tsx, packages/newsroom-signup/src/ApplyToTCR/ApplyToTCRWhitelisted.tsx, packages/newsroom-signup/src/ApplyToTCR/index.tsx, packages/newsroom-signup/src/NewsroomProfile/RosterMember.tsx, packages/utils/src/viewHelpers.tsx
- In apply flow, show new "whitelisted" state instead of "apply to TCR" if newsroom is whitelisted
- Fix multisig transaction issue when republishing charter from apply flow
- Some style fixes
=> Apply flow + dapp fixes

packages/sdk/src/react/boosts/payments/BoostPaymentRequest.tsx
-  untested, but only way to easily test is to put it on staging. plus it's broken already so wouldn't be breaking anything anyways
=> fix: test stripe payment request fix

packages/sdk/src/react/boosts/payments/BoostPaymentRequest.tsx
=> fix: fix stripe again

packages/sdk/src/react/boosts/payments/BoostPayFormStripe.tsx, packages/sdk/src/react/boosts/payments/BoostPaymentRequest.tsx
- show success/error modals when appropriate
=> fix: cleanup payment request

packages/dapp/src/components/header/NavDrawer.tsx
- remove tasks from nav drawer
=> fix nav drawer

packages/sdk/docs/source/civil_sdk_package.rst, packages/sdk/package.json
=> fix(sdk): update build script name

packages/contracts/package.json, packages/contracts/test/utils/contractutils.ts, packages/contracts/test/utils/getethapi.ts, packages/core/doc/examples/low-level/typed_contracts.ts, packages/core/package.json, packages/core/src/civil.ts, packages/core/src/contracts/basecontract.ts, packages/core/src/contracts/multisig/multisig.ts, packages/core/src/contracts/newsroom.ts, packages/core/src/contracts/tcr/civilTCR.ts, packages/core/src/contracts/tcr/council.ts, packages/core/src/contracts/utils/contracts.ts, packages/core/src/templates/artifacts.handlebars, packages/core/src/templates/contract/contract.handlebars, packages/core/src/templates/contract/multisigproxy.handlebars, packages/dapp/package.json, packages/dev-utils/package.json, packages/dev-utils/src/test/index.ts, packages/ethapi/package.json, packages/ethapi/src/abidecoder.ts, packages/ethapi/src/ethapi.ts, packages/ethapi/tsconfig.json, packages/kirby/package.json, packages/typescript-types/package.json, packages/typescript-types/src/index.ts, yarn.lock
upgrade web3 to 1.2.2. this removes the need for `@types/web3`
includes a kirby bump as well that fixes an issue where cookies where being set as `session` instead of expiring
=> feat(core): web3 1.2.2

packages/components/src/Account/Auth/UserSetAvatar.tsx, packages/components/src/Account/Auth/UserSetEmail.tsx, packages/components/src/Account/LoadUser.tsx, packages/components/src/TCRUserDashboard/DashboardStyledComponents.tsx, packages/components/src/TCRUserDashboard/DashboardUserInfoSummary.tsx, packages/components/src/TCRUserDashboard/DashboardUserProfileSummary.tsx, packages/components/src/TCRUserDashboard/index.ts, packages/dapp/src/components/Auth/SetAvatar.tsx, packages/dapp/src/components/Auth/SetEmail.tsx, packages/dapp/src/components/Dashboard/Dashboard.tsx, packages/dapp/src/components/Dashboard/UserInfoSummary.tsx, packages/dapp/src/components/Dashboard/UserProfileSummary.tsx, yarn.lock
- editing/setting email and avatar from dashboard is functional, but not implemented as designed (since design is not ready yet)
- display of email address is not as designed (since designs not updated to reflect this field yet)
=> feat: show user profile on dashboard with ability to edit

packages/components/src/TCRUserDashboard/DashboardStyledComponents.tsx, packages/components/src/TCRUserDashboard/DashboardTextComponents.tsx, packages/dapp/src/components/Dashboard/ChallengesWithRewardsToClaim.tsx, packages/dapp/src/components/Dashboard/ChallengesWithTokensToRescue.tsx, packages/dapp/src/components/Dashboard/Dashboard.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/Dashboard/MyTasks.tsx, packages/dapp/src/components/Dashboard/MyTasksList.tsx, packages/elements/src/buttons/Button.tsx, packages/elements/src/colors/index.ts, packages/elements/src/text/fonts.ts
- replace "tasks" subtabs with a dropdown + button (for token transfer)
- modifications to how width is controlled so all dashboard tabs contents display with same width
- the changes to MyTasks are a little bit hacky, but it's a very unique one-off component, and I'm not sure it's worth spending time making it very reusable
=> feat: tasks dropdown

packages/components/src/TCRUserDashboard/DashboardActivity.tsx, packages/components/src/TCRUserDashboard/DashboardStyledComponents.tsx, packages/components/src/TCRUserDashboard/DashboardUserProfileSummary.tsx, packages/components/src/Tabs/Tab.tsx, packages/dapp/src/components/Dashboard/ChallengesWithRewardsToClaim.tsx, packages/dapp/src/components/Dashboard/ChallengesWithTokensToRescue.tsx, packages/dapp/src/components/Dashboard/DashboardActivity.tsx, packages/dapp/src/components/Dashboard/MyTasks.tsx, packages/dapp/src/components/Dashboard/UserInfoSummary.tsx, packages/dapp/src/components/header/UserAccount.tsx, packages/dapp/src/components/header/styledComponents.tsx, packages/elements/src/colors/index.ts
- add badge to tasks tab
- handle user with no avatar / handle / tasks
=> feat: dashboard style updates

.circleci/config.yml, packages/dapp/package.json
=> use medium+ circleci containers

packages/components/src/Payments/PaymentsEthForm.tsx
this is needed so that Portis works
=> fix(dapp): don't require injected ethereum

packages/components/src/Payments/PaymentsAmount.tsx, packages/dapp/src/embeds/StoryBoostLoader.tsx, packages/elements/src/buttons/PaymentButton.tsx, packages/kirby/src/common/text/index.tsx, packages/kirby/src/views/identity/Login.tsx, packages/sdk/src/react/StoryBoost/StoryBoost.tsx, packages/sdk/src/react/boosts/BoostEmbedIframe.tsx
Main changes are "good journalism costs money..." intro text, better boost button CTA, and clickable "support this newsroom" text. Otherwise misc spacing and sizing and other tweaks.
=> 1337 styles for story boost embeds [CIVIL-1337]

packages/dapp/src/components/StoryFeed/StoryFeedMarquee.tsx
* redirect some pages to learn.civil.co https://github.com/joincivil/Civil/pull/1605
=> Production Release - 2020-01-15 11:15am

packages/components/src/Payments/Payments.tsx, packages/components/src/Payments/PaymentsTextComponents.tsx, packages/components/src/Payments/types.ts, packages/dapp/devops/nginx.conf
* missed a couple of redirects https://github.com/joincivil/Civil/commit/5e269345f601e019d1028d9a28b285cd37f68d7d
* update credit card min https://github.com/joincivil/Civil/commit/50b052caeeab727df705fb44ea1a39c40b132033
=> 2020-01-15 12:46pm Production Release #2

packages/kirby/src/plugins/CivilID.ts
This changes the signature we present to the user to log in sign up. Previously was "Sign up to Civil @ {timestamp}" or "Log in to Civil @ {timestamp}". Now it is "Authenticate to {domain} @ {timestamp}". This allows us to reuse the signature if an account already exists (signup -> login). Additionally, it makes it clearer when authenticating to 3rd party sites-  you aren't signing up or logging in (from Kirby's perspective), you are just authenticating and the provider decides what to do with the signature. 
NOTE: this needs to ride with civil-api-server changes https://github.com/joincivil/civil-api-server/pull/324
=> feat(kirby): use same signature for login and signup

packages/newsroom-signup/src/RepublishCharterNotice.tsx, packages/newsroom-signup/src/SmartContract/AddMember.tsx, packages/newsroom-signup/src/SmartContract/AddMembersToContract.tsx, packages/utils/src/viewHelpers.tsx
While debugging and testing the add-new-newsroom-admin flow I came across several bugs and missing features that would be helpful both for users and for us debugging, see commit messages for details.
=> Improvements to Manage Newsroom > Smart Contract roles

packages/dapp/src/components/Dashboard/Account/Account.tsx, packages/dapp/src/components/Dashboard/Account/AccountStyledComponents.tsx, packages/dapp/src/components/Dashboard/Account/AccountTextComponents.tsx, packages/dapp/src/components/Dashboard/Account/AccountTransactions.tsx
Lives on the new `/account` page.
=> Add transaction history [CIVIL-1427]

packages/components/src/Payments/PaymentsInputValidationUI.tsx, packages/components/src/Payments/PaymentsLoadStripePayRequest.tsx, packages/components/src/Payments/PaymentsStripeForm.tsx, packages/components/src/Payments/PaymentsStyledComponents.tsx, yarn.lock
- removed pay request FOC
- fixed or styling
- worked with Rob to consolidate Stripe pay form!
=> refactor: payment improvements

packages/components/src/Account/Auth/ConfirmEmailToken.tsx, packages/dapp/src/components/Auth/ConfirmEmail.tsx, packages/dapp/src/components/header/NavBar.tsx, packages/dapp/src/components/header/UserNotificationBar.tsx, packages/utils/src/apolloClient.ts
- notification bar for confirm email
=> Prod Release Mar 20 2020
